const cidadesPorEstado = {
    'CE': [
	    { sigla: 'AQZ', nome: 'Aquiraz' },
	    { sigla: 'BBB', nome: 'Beberibe' },
	    { sigla: 'CVL', nome: 'Cascavel' },
	    { sigla: 'CUC', nome: 'Caucaia' },
	    { sigla: 'CZH', nome: 'Chorozinho' },
	    { sigla: 'ESB', nome: 'Eusebio' },
	    { sigla: 'FLA', nome: 'Fortaleza' },
	    { sigla: 'GBA', nome: 'Guaiuba' },"
	    { sigla: 'HZT', nome: 'Horizonte' },
	    { sigla: 'IAGA', nome: 'Itaitinga' },
	    { sigla: 'MCW', nome: 'Maracanaú' },
	    { sigla: 'MUE', nome: 'Maranguape' },
	    { sigla: 'PJS', nome: 'Pacajus' },
	    { sigla: 'PUB', nome: 'Pacatuba' },
	    { sigla: 'PDJ', nome: 'Pindoretama' },
	    { sigla: 'SGA', nome: 'São Gonçalo do Amarante' },
	    { sigla: 'ACP', nome: 'Acarape' },
	    { sigla: 'AUS', nome: 'Apuiarés' },
	    { sigla: 'AAB', nome: 'Acaroia' },
	    { sigla: 'ATU', nome: 'Aratuba' },
	    { sigla: 'BRK', nome: 'Barreira' },
	    { sigla: 'BTT', nome: 'Baturité' },
	    { sigla: 'CIE', nome: 'Canindé' },
	    { sigla: 'CSR', nome: 'Capistrano' },
	    { sigla: 'CID', nome: 'Caridade' },
	    { sigla: 'GNL', nome: 'General Sampaio' },
	    { sigla: 'GAG', nome: 'Guaramiranga' },
	    { sigla: 'MUN', nome: 'Mulungu' },
	    { sigla: 'OCR', nome: 'Ocara' },
	    { sigla: 'PTY', nome: 'Pacoti' },
	    { sigla: 'PMC', nome: 'Palmácia' },
	    { sigla: 'POY', nome: 'Paramoti' },
	    { sigla: 'RDC', nome: 'Redenção' },
	    { sigla: 'IGE', nome: 'Itapagé' },
	    { sigla: 'PUU', nome: 'Paracuru' },
	    { sigla: 'PWB', nome: 'Paraipaba' },
	    { sigla: 'POE', nome: 'Pentecoste' },
	    { sigla: 'SRU', nome: 'São Luís do Curu' },
	    { sigla: 'TJU', nome: 'Tejuçuoca' },
	    { sigla: 'TRY', nome: 'Trairi' },
	    { sigla: 'TUK', nome: 'Tururu' },
	    { sigla: 'URM', nome: 'Umirim' },
	    { sigla: 'UUA', nome: 'Uruburetama' },
	    { sigla: 'ATO', nome: 'Alto Santo' },
	    { sigla: 'ACA', nome: 'Aracati' },
	    { sigla: 'FORT', nome: 'Fortim' },
	    { sigla: 'ICN', nome: 'Ibicuitinga' },
	    { sigla: 'ICP', nome: 'Icapuí' },
	    { sigla: 'ICA', nome: 'Iracema' },
	    { sigla: 'IAX', nome: 'Itaicaba' },
	    { sigla: 'JGN', nome: 'Jaguaruana' },
	    { sigla: 'LNT', nome: 'Limoeiro do Norte' },
	    { sigla: 'MVA', nome: 'Morada Nova' },
	    { sigla: 'PHN', nome: 'Palhano' },
	    { sigla: 'PTZ', nome: 'Potiretama' },
	    { sigla: 'QXE', nome: 'Quixeré' },
	    { sigla: 'RUS', nome: 'Russas' },
	    { sigla: 'SUB', nome: 'São João do Jaguaribe' },
	    { sigla: 'TNT', nome: 'Tabuleiro do Norte' },
	    { sigla: 'ABY', nome: 'Abaiara' },
	    { sigla: 'AUR', nome: 'Aurora' },
	    { sigla: 'BBH', nome: 'Barbalha' },
	    { sigla: 'BAO', nome: 'Barro' },
	    { sigla: 'BJS', nome: 'Brejo Santo' },
	    { sigla: 'CAC', nome: 'Caririaçu' },
	    { sigla: 'CTO', nome: 'Crato' },
	    { sigla: 'GJO', nome: 'Granjeiro' },
	    { sigla: 'JDM', nome: 'Jardim' },
	    { sigla: 'JAT', nome: 'Jati' },
	    { sigla: 'JNE', nome: 'Juazeiro do Norte' },
	    { sigla: 'MRT', nome: 'Mauriti' },
	    { sigla: 'MGS', nome: 'Milagres' },
	    { sigla: 'MAH', nome: 'Missão Velha' },
	    { sigla: 'PFT', nome: 'Penaforte' },
	    { sigla: 'PTX', nome: 'Porteiras' },
	    { sigla: 'VZG', nome: 'Várzea Alegre' },
	    { sigla: 'AIB', nome: 'Aiuaba' },
	    { sigla: 'ANY', nome: 'Altaneira' },
	    { sigla: 'ANE', nome: 'Antonina do Norte' },
	    { sigla: 'ARP', nome: 'Araripe' },
	    { sigla: 'ASE', nome: 'Assaré' },
	    { sigla: 'CMS', nome: 'Campos Sales' },
	    { sigla: 'FBO', nome: 'Farias Brito' },
	    { sigla: 'NID', nome: 'Nova Olinda' },
	    { sigla: 'PGY', nome: 'Potengi' },
	    { sigla: 'SIQ', nome: 'Salitre' },
	    { sigla: 'SCI', nome: 'Santana do Cariri' },
	    { sigla: 'TRR', nome: 'Tarrafas' },
	    { sigla: 'ACX', nome: 'Alcântaras' },
	    { sigla: 'AOW', nome: 'Amontada' },
	    { sigla: 'CIW', nome: 'Carire' },
	    { sigla: 'CATN', nome: 'Catunda' },
	    { sigla: 'CEA', nome: 'Coreau' },
	    { sigla: 'FRQ', nome: 'Forquilha' },
	    { sigla: 'GRO', nome: 'Groairas' },
	    { sigla: 'HDA', nome: 'Hidrolândia' },
	    { sigla: 'ICB', nome: 'Irauçuba' },
	    { sigla: 'IOP', nome: 'Itapipoca' },
	    { sigla: 'MSS', nome: 'Massapê' },
	    { sigla: 'MEU', nome: 'Meruoca' },
	    { sigla: 'MIK', nome: 'Miraíma' },
	    { sigla: 'MUJ', nome: 'Moraújo' },
	    { sigla: 'RRB', nome: 'Reriutaba' },
	    { sigla: 'SNQ', nome: 'Santa Quitéria' },
	    { sigla: 'SAU', nome: 'Santana do Acaraú' },
	    { sigla: 'SOL', nome: 'Sobral' },
	    { sigla: 'VJT', nome: 'Varjota' },
	    { sigla: 'CUB', nome: 'Carnaubal' },
	    { sigla: 'COZ', nome: 'Croatá' },
	    { sigla: 'FHH', nome: 'Frecheirinha' },
	    { sigla: 'GCA', nome: 'Graça' },
	    { sigla: 'GRN', nome: 'Guaraciaba do Norte' },
	    { sigla: 'INX', nome: 'Ibiapina' },
	    { sigla: 'MUM', nome: 'Mucambo' },
	    { sigla: 'PUJ', nome: 'Pacujá' },
	    { sigla: 'SBN', nome: 'São Benedito' },
	    { sigla: 'TIG', nome: 'Tianguá' },
	    { sigla: 'UBJ', nome: 'Ubajara' },
	    { sigla: 'VCC', nome: 'Viçosa do Ceará' },
	    { sigla: 'AAU', nome: 'Acaraú' },
	    { sigla: 'BQN', nome: 'Barroquinha' },
	    { sigla: 'BCZ', nome: 'Bela Cruz' },
	    { sigla: 'CCM', nome: 'Camocim' },
	    { sigla: 'CHA', nome: 'Chaval' },
	    { sigla: 'CZW', nome: 'Cruz' },
	    { sigla: 'GNJ', nome: 'Granja' },
	    { sigla: 'IMW', nome: 'Itarema' },
	    { sigla: 'JIJO', nome: 'Jijoca de Jericoacoara' },
	    { sigla: 'MAC', nome: 'Marco' },
	    { sigla: 'MOP', nome: 'Martinópole' },
	    { sigla: 'MNH', nome: 'Morrinhos' },
	    { sigla: 'SNR', nome: 'Senador Sá' },
	    { sigla: 'UUO', nome: 'Uruoca' },
	    { sigla: 'ACR', nome: 'Acopiara' },
	    { sigla: 'CYS', nome: 'Cariús' },
	    { sigla: 'CYN', nome: 'Catarina' },
	    { sigla: 'IAU', nome: 'Iguatu' },
	    { sigla: 'JAS', nome: 'Jucás' },
	    { sigla: 'MBC', nome: 'Mombaça' },
	    { sigla: 'PDB', nome: 'Pedra Branca' },
	    { sigla: 'PQT', nome: 'Piquet Carneiro' },
	    { sigla: 'QXO', nome: 'Quixelô' },
	    { sigla: 'SOI', nome: 'Saboeiro' },
	    { sigla: 'BXO', nome: 'Baixio' },
	    { sigla: 'CED', nome: 'Cedro' },
	    { sigla: 'DPIP', nome: 'Deputado Irapuan Pinheiro' },
	    { sigla: 'ERR', nome: 'Ererê' },
	    { sigla: 'ICO', nome: 'Ico' },
	    { sigla: 'IMI', nome: 'Ipaumirim' },
	    { sigla: 'JAG', nome: 'Jaguaratama' },
	    { sigla: 'JGB', nome: 'Jaguaribara' },
	    { sigla: 'JGE', nome: 'Jaguaribe' },
	    { sigla: 'LVM', nome: 'Lavras da Mangabeira' },
	    { sigla: 'MHW', nome: 'Milha' },
	    { sigla: 'OOS', nome: 'Orós' },
	    { sigla: 'PEO', nome: 'Pereiro' },
	    { sigla: 'SOP', nome: 'Solonópole' },
	    { sigla: 'UMI', nome: 'Umari' },
	    { sigla: 'CTS', nome: 'Crateús' },
	    { sigla: 'IDA', nome: 'Independência' },
	    { sigla: 'NOE', nome: 'Novo Oriente' },
	    { sigla: 'QTS', nome: 'Quiterianópolis' },
	    { sigla: 'ARAE', nome: 'Ararendá' },
	    { sigla: 'IPZ', nome: 'Ipaporanga' },
	    { sigla: 'IPU', nome: 'Ipu' },
	    { sigla: 'IUE', nome: 'Ipueiras' },
	    { sigla: 'MHT', nome: 'Monsenhor Tabosa' },
	    { sigla: 'NRU', nome: 'Nova Russas' },
	    { sigla: 'PSF', nome: 'Pires Ferreira' },
	    { sigla: 'PGX', nome: 'Poranga' },
	    { sigla: 'TBL', nome: 'Tamboril' },
	    { sigla: 'AEZ', nome: 'Arneiroz' },
	    { sigla: 'PBU', nome: 'Parambu' },
	    { sigla: 'TUA', nome: 'Tauá' },
	    { sigla: 'BIU', nome: 'Banabuiú' },
	    { sigla: 'BVG', nome: 'Boa Viagem' },
	    { sigla: 'CHOO', nome: 'Choro' },
	    { sigla: 'IBW', nome: 'Ibaetama' },
	    { sigla: 'ITN', nome: 'Itapiúna' },
	    { sigla: 'ITK', nome: 'Itatira' },
	    { sigla: 'MDX', nome: 'Madalena' },
	    { sigla: 'QXA', nome: 'Quixadá' },
	    { sigla: 'QXM', nome: 'Quixeramobim' },
	    { sigla: 'SPM', nome: 'Senador Pompeu' }
    ],
    'RN': [
	    { sigla: 'ARE', nome: 'Ares' },
	    { sigla: 'BFA', nome: 'Baia Formosa' },
	    { sigla: 'BRC', nome: 'Barcelona' },
	    { sigla: 'BFN', nome: 'Bento Fernandes' },
	    { sigla: 'BOU', nome: 'Bom Jesus' },
	    { sigla: 'BJN', nome: 'Brejinho' },
	    { sigla: 'CGM', nome: 'Canguaretama' },
	    { sigla: 'CAY', nome: 'Ceara-Mirim' },
	    { sigla: 'ESO', nome: 'Espirito Santo' },
	    { sigla: 'EXZ', nome: 'Extremoz' },
	    { sigla: 'GOH', nome: 'Goianinha' },
	    { sigla: 'IEL', nome: 'Ielmo Marinho' },
	    { sigla: 'BASD', nome: 'Januario Cicco' },
	    { sigla: 'JAP', nome: 'Japi' },
	    { sigla: 'JOA', nome: 'Joao Camara' },
	    { sigla: 'JUCI', nome: 'Jundia' },
	    { sigla: 'LGD', nome: "Lagoa D'Anta" },
	    { sigla: 'LGE', nome: 'Lagoa de Pedras' },
	    { sigla: 'LEL', nome: 'Lagoa de Velhos' },
	    { sigla: 'LLG', nome: 'Lagoa Salgada' },
	    { sigla: 'LES', nome: 'Lajes Pintadas' },
	    { sigla: 'MCI', nome: 'Macaiba' },
	    { sigla: 'MXE', nome: 'Maxaranguape' },
	    { sigla: 'MTH', nome: 'Montanhas' },
	    { sigla: 'MOG', nome: 'Monte Alegre' },
	    { sigla: 'MMS', nome: 'Monte das Gameleiras' },
	    { sigla: 'NTL', nome: 'Natal' },
	    { sigla: 'NSF', nome: 'Nisia Floresta' },
	    { sigla: 'NCZ', nome: 'Nova Cruz' },
	    { sigla: 'PWM', nome: 'Parnamirim' },
	    { sigla: 'PEF', nome: 'Passa e Fica' },
	    { sigla: 'PGM', nome: 'Passagem' },
	    { sigla: 'PDH', nome: 'Pedro Velho' },
	    { sigla: 'POC', nome: 'Poco Branco' },
	    { sigla: 'SECD', nome: 'Presidente Juscelino' },
	    { sigla: 'PZA', nome: 'Pureza' },
	    { sigla: 'RHE', nome: 'Riachuelo' },
	    { sigla: 'ROFG', nome: 'Rio do Fogo' },
	    { sigla: 'RYA', nome: 'Ruy Barbosa' },
	    { sigla: 'SNZ', nome: 'Santa Cruz' },
	    { sigla: 'SAAI', nome: 'Santa Maria' },
	    { sigla: 'SOT', nome: 'Santo Antonio' },
	    { sigla: 'SWB', nome: 'Sao Bento do Trairi' },
	    { sigla: 'SGM', nome: 'Sao Goncalo do Amarante' },
	    { sigla: 'SII', nome: 'Sao Jose de Mipibu' },
	    { sigla: 'SAC', nome: 'Sao Jose do Campestre' },
	    { sigla: 'SMDT', nome: 'São Miguel do Gostoso' },
	    { sigla: 'SLG', nome: 'Sao Paulo do Potengi' },
	    { sigla: 'SPK', nome: 'Sao Pedro' },
	    { sigla: 'STM', nome: 'Sao Tome' },
	    { sigla: 'SOZ', nome: 'Senador Eloi de Souza' },
	    { sigla: 'SGV', nome: 'Senador Georgino Avelino' },
	    { sigla: 'SBK', nome: 'Serra de Sao Bento' },
	    { sigla: 'SWR', nome: 'Serrinha' },
	    { sigla: 'SYO', nome: 'Sitio Novo' },
	    { sigla: 'TAI', nome: 'Taipu' },
	    { sigla: 'TNG', nome: 'Tangara' },
	    { sigla: 'TUL', nome: 'Tibau do Sul' },
	    { sigla: 'TUS', nome: 'Touros' },
	    { sigla: 'VZA', nome: 'Varzea' },
	    { sigla: 'VRZ', nome: 'Vera Cruz' },
	    { sigla: 'VLR', nome: 'Vila Flor' },
	    { sigla: 'ACU', nome: 'Acu' },
	    { sigla: 'AGV', nome: 'Agua Nova' },
	    { sigla: 'AXD', nome: 'Alexandria' },
	    { sigla: 'ALF', nome: 'Almino Afonso' },
	    { sigla: 'ANM', nome: 'Antonio Martins' },
	    { sigla: 'APD', nome: 'Apodi' },
	    { sigla: 'ABC', nome: 'Areia Branca' },
	    { sigla: 'CWD', nome: 'Augusto Severo' },
	    { sigla: 'BRN', nome: 'Barauna' },
	    { sigla: 'CRB', nome: 'Caraubas' },
	    { sigla: 'CNU', nome: 'Carnaubais' },
	    { sigla: 'CJA', nome: 'Coronel Joao Pessoa' },
	    { sigla: 'DRV', nome: 'Doutor Severiano' },
	    { sigla: 'ECT', nome: 'Encanto' },
	    { sigla: 'FPG', nome: 'Felipe Guerra' },
	    { sigla: 'FAD', nome: 'Francisco Dantas' },
	    { sigla: 'FRG', nome: 'Frutuoso Gomes' },
	    { sigla: 'GXS', nome: 'Governador Dix-Sept Rosado' },
	    { sigla: 'GSS', nome: 'Grossos' },
	    { sigla: 'INC', nome: 'Ipanguacu' },
	    { sigla: 'ITJY', nome: 'Itaja' },
	    { sigla: 'ITW', nome: 'Itau' },
	    { sigla: 'JIS', nome: 'Janduis' },
	    { sigla: 'JOD', nome: 'Joao Dias' },
	    { sigla: 'JOP', nome: 'Jose da Penha' },
	    { sigla: 'LUR', nome: 'Lucrecia' },
	    { sigla: 'LGO', nome: 'Luis Gomes' },
	    { sigla: 'MASA', nome: 'Major Sales' },
	    { sigla: 'MCV', nome: 'Marcelino Vieira' },
	    { sigla: 'MTN', nome: 'Martins' },
	    { sigla: 'MTR', nome: 'Messias Targino' },
	    { sigla: 'MRO', nome: 'Mossoro' },
	    { sigla: 'OAB', nome: "Olho-D'Agua do Borges" },
	    { sigla: 'PWN', nome: 'Parana' },
	    { sigla: 'PAW', nome: 'Parau' },
	    { sigla: 'PTW', nome: 'Patu' },
	    { sigla: 'PFR', nome: 'Pau dos Ferros' },
	    { sigla: 'PLK', nome: 'Piloes' },
	    { sigla: 'PLW', nome: 'Portalegre' },
	    { sigla: 'RFL', nome: 'Rafael Fernandes' },
	    { sigla: 'RFG', nome: 'Rafael Godeiro' },
	    { sigla: 'RCZ', nome: 'Riacho da Cruz' },
	    { sigla: 'RAD', nome: 'Riacho de Santana' },
	    { sigla: 'RFF', nome: 'Rodolfo Fernandes' },
	    { sigla: 'SFT', nome: 'Sao Francisco do Oeste' },
	    { sigla: 'SMU', nome: 'Sao Miguel' },
	    { sigla: 'SFA', nome: 'Sao Rafael' },
	    { sigla: 'SYF', nome: 'Serra do Mel' },
	    { sigla: 'SEPS', nome: 'Serrinha dos Pintos' },
	    { sigla: 'SWV', nome: 'Severiano Melo' },
	    { sigla: 'TLG', nome: 'Taboleiro Grande' },
	    { sigla: 'TNN', nome: 'Tenente Ananias' },
	    { sigla: 'TIBA', nome: 'Tibau' },
	    { sigla: 'TRIU', nome: 'Triunfo Potiguar' },
	    { sigla: 'UZL', nome: 'Umarizal' },
	    { sigla: 'UNM', nome: 'Upanema' },
	    { sigla: 'VAVR', nome: 'Venha-Ver' },
	    { sigla: 'VIO', nome: 'Vicosa' },
	    { sigla: 'ACI', nome: 'Acari' },
	    { sigla: 'BODO', nome: 'Bodo' },
	    { sigla: 'CIC', nome: 'Caico' },
	    { sigla: 'CDW', nome: 'Campo Redondo' },
	    { sigla: 'CUO', nome: 'Carnauba dos Dantas' },
	    { sigla: 'CCW', nome: 'Cerro Cora' },
	    { sigla: 'CEZ', nome: 'Coronel Ezequiel' },
	    { sigla: 'CZE', nome: 'Cruzeta' },
	    { sigla: 'CSS', nome: 'Currais Novos' },
	    { sigla: 'EQD', nome: 'Equador' },
	    { sigla: 'FNA', nome: 'Florania' },
	    { sigla: 'IXP', nome: 'Ipueira' },
	    { sigla: 'JAN', nome: 'Jacana' },
	    { sigla: 'JMH', nome: 'Jardim de Piranhas' },
	    { sigla: 'JMS', nome: 'Jardim do Serido' },
	    { sigla: 'JTU', nome: 'Jucurutu' },
	    { sigla: 'LGN', nome: 'Lagoa Nova' },
	    { sigla: 'OOB', nome: 'Ouro Branco' },
	    { sigla: 'PRH', nome: 'Parelhas' },
	    { sigla: 'SKA', nome: 'Santana do Serido' },
	    { sigla: 'SXF', nome: 'Sao Fernando' },
	    { sigla: 'SSY', nome: 'Sao Joao do Sabugi' },
	    { sigla: 'SKS', nome: 'Sao Jose do Serido' },
	    { sigla: 'SOV', nome: 'Sao Vicente' },
	    { sigla: 'SAW', nome: 'Serra Negra do Norte' },
	    { sigla: 'SECD', nome: 'Serra Caiada' },
	    { sigla: 'TNLO', nome: 'Tenente Laurentino Cruz' },
	    { sigla: 'TTT', nome: 'Timbauba dos Batistas' },
	    { sigla: 'AFZ', nome: 'Afonso Bezerra' },
	    { sigla: 'ADG', nome: 'Alto do Rodrigues' },
	    { sigla: 'ANO', nome: 'Angicos' },
	    { sigla: 'CCRA', nome: 'Caicara do Norte' },
	    { sigla: 'CCV', nome: 'Caicara do Rio do Vento' },
	    { sigla: 'FEPE', nome: 'Fernando Pedroza' },
	    { sigla: 'GAL', nome: 'Galinhos' },
	    { sigla: 'GME', nome: 'Guamare' },
	    { sigla: 'JDR', nome: 'Jandaira' },
	    { sigla: 'JMG', nome: 'Jardim de Angicos' },
	    { sigla: 'LJE', nome: 'Lajes' },
	    { sigla: 'MCU', nome: 'Macau' },
	    { sigla: 'PRZ', nome: 'Parazinho' },
	    { sigla: 'PGR', nome: 'Pedra Grande' },
	    { sigla: 'PAP', nome: 'Pedra Preta' },
	    { sigla: 'PDL', nome: 'Pedro Avelino' },
	    { sigla: 'PNS', nome: 'Pendencias' },
	    { sigla: 'POMA', nome: 'Porto do Mangue' },
	    { sigla: 'SMS', nome: 'Santana do Matos' },
	    { sigla: 'SBE', nome: 'Sao Bento do Norte' }
    ],
    'PB': [
	    { sigla: 'AHD', nome: 'Alhandra' },
	    { sigla: 'BAI', nome: 'Baía da Traição' },
	    { sigla: 'BEX', nome: 'Bayeux' },
	    { sigla: 'CPX', nome: 'Caaporá' },
	    { sigla: 'CBD', nome: 'Cabedelo' },
	    { sigla: 'CAPI', nome: 'Capim' },
	    { sigla: 'CWX', nome: 'Conde' },
	    { sigla: 'CZD', nome: 'Cruz do Espírito Santo' },
	    { sigla: 'CUTM', nome: 'Cuité de Mamanguape' },
	    { sigla: 'CUCI', nome: 'Curral de Cima' },
	    { sigla: 'IOO', nome: 'Itapororoca' },
	    { sigla: 'JAC', nome: 'Jacaraú' },
	    { sigla: 'JPA', nome: 'João Pessoa' },
	    { sigla: 'LUN', nome: 'Lucena' },
	    { sigla: 'MME', nome: 'Mamanguape' },
	    { sigla: 'MRCA', nome: 'Marcação' },
	    { sigla: 'MCX', nome: 'Mataraca' },
	    { sigla: 'PFO', nome: 'Pedras de Fogo' },
	    { sigla: 'PERG', nome: 'Pedro Régis' },
	    { sigla: 'PMU', nome: 'Pitimbu' },
	    { sigla: 'RDPC', nome: 'Riachão do Poço' },
	    { sigla: 'RTT', nome: 'Rio Tinto' },
	    { sigla: 'SRI', nome: 'Santa Rita' },
	    { sigla: 'SMP', nome: 'São Miguel de Taipu' },
	    { sigla: 'SPH', nome: 'Sapé' },
	    { sigla: 'SOBR', nome: 'Sobrado' },
	    { sigla: 'AGG', nome: 'Alagoa Grande' },
	    { sigla: 'AHA', nome: 'Alagoinha' },
	    { sigla: 'AAG', nome: 'Aracagi' },
	    { sigla: 'BEM', nome: 'Belém' },
	    { sigla: 'BBE', nome: 'Borboirema' },
	    { sigla: 'CIX', nome: 'Caicara' },
	    { sigla: 'CLSD', nome: 'Caldas Brandão' },
	    { sigla: 'CIG', nome: 'Cuitégi' },
	    { sigla: 'DES', nome: 'Duas Estradas' },
	    { sigla: 'GBI', nome: 'Guarabira' },
	    { sigla: 'GIH', nome: 'Gurinhém' },
	    { sigla: 'IYN', nome: 'Itabaiana' },
	    { sigla: 'JNG', nome: 'Juripiranga' },
	    { sigla: 'LDT', nome: 'Lagoa de Dentro' },
	    { sigla: 'LOGA', nome: 'Logradouro' },
	    { sigla: 'MAI', nome: 'Mari' },
	    { sigla: 'MGY', nome: 'Mogeiro' },
	    { sigla: 'MUL', nome: 'Mulungu' },
	    { sigla: 'PYR', nome: 'Pilar' },
	    { sigla: 'PYL', nome: 'Piloes' },
	    { sigla: 'POZ', nome: 'Piloezinhos' },
	    { sigla: 'PPB', nome: 'Pirpirituba' },
	    { sigla: 'SSX', nome: 'Salgado de São Félix' },
	    { sigla: 'SJWR', nome: 'São José dos Ramos' },
	    { sigla: 'SDZ', nome: 'Serra da Raiz' },
	    { sigla: 'SRY', nome: 'Serraria' },
	    { sigla: 'SERT', nome: 'Sertãozinho' },
	    { sigla: 'AGO', nome: 'Alagoa Nova' },
	    { sigla: 'ALCA', nome: 'Alcantil' },
	    { sigla: 'ALGJ', nome: 'Algodão de Jandaíra' },
	    { sigla: 'ARX', nome: 'Arara' },
	    { sigla: 'AAN', nome: 'Araruna' },
	    { sigla: 'AEI', nome: 'Areia' },
	    { sigla: 'AEA', nome: 'Areial' },
	    { sigla: 'AES', nome: 'Aroeiras' },
	    { sigla: 'BNN', nome: 'Bananeiras' },
	    { sigla: 'BARS', nome: 'Baraúna' },
	    { sigla: 'BEN', nome: 'Barra de Santa Rosa' },
	    { sigla: 'BRSN', nome: 'Barra de Santana' },
	    { sigla: 'BVTA', nome: 'Boa Vista' },
	    { sigla: 'BQO', nome: 'Boqueirão' },
	    { sigla: 'CIB', nome: 'Cacimba de Dentro' },
	    { sigla: 'CGE', nome: 'Campina Grande' },
	    { sigla: 'TAM', nome: 'Campo de Santana' },
	    { sigla: 'CSRE', nome: 'Casserengue' },
	    { sigla: 'CATR', nome: 'Caturité' },
	    { sigla: 'CBT', nome: 'Cubati' },
	    { sigla: 'CUT', nome: 'Cuité' },
	    { sigla: 'DMIO', nome: 'Damião' },
	    { sigla: 'DNS', nome: 'Dona Inês' },
	    { sigla: 'ERA', nome: 'Esperança' },
	    { sigla: 'FGS', nome: 'Fagundes' },
	    { sigla: 'FRH', nome: 'Frei Martinho' },
	    { sigla: 'GABR', nome: 'Gado Bravo' },
	    { sigla: 'INA', nome: 'Ingá' },
	    { sigla: 'ITX', nome: 'Itatuba' },
	    { sigla: 'JZT', nome: 'Juarez Távora' },
	    { sigla: 'JZH', nome: 'Juazeirinho' },
	    { sigla: 'LGC', nome: 'Lagoa Seca' },
	    { sigla: 'MNU', nome: 'Massaranduba' },
	    { sigla: 'MATN', nome: 'Matinhas' },
	    { sigla: 'MDK', nome: 'Montadas' },
	    { sigla: 'NUB', nome: 'Natuba' },
	    { sigla: 'NVF', nome: 'Nova Floresta' },
	    { sigla: 'NVL', nome: 'Nova Palmeira' },
	    { sigla: 'OVD', nome: 'Olivedos' },
	    { sigla: 'PVD', nome: 'Pedra Lavrada' },
	    { sigla: 'PCI', nome: 'Picuí' },
	    { sigla: 'PHS', nome: 'Pocinhos' },
	    { sigla: 'PXA', nome: 'Puxinana' },
	    { sigla: 'QUS', nome: 'Queimadas' },
	    { sigla: 'RMG', nome: 'Remígio' },
	    { sigla: 'RAAO', nome: 'Riacho' },
	    { sigla: 'RCBE', nome: 'Riachão do Bacamarte' },
	    { sigla: 'RISA', nome: 'Riacho de Santo Antônio' },
	    { sigla: 'SCUM', nome: 'Santa Cecília' },
	    { sigla: 'SKL', nome: 'São Sebastião de Lagoa de Roça' },
	    { sigla: 'SIDO', nome: 'Seridó' },
	    { sigla: 'SDK', nome: 'Serra Redonda' },
	    { sigla: 'SOA', nome: 'Solânea' },
	    { sigla: 'SOD', nome: 'Soledade' },
	    { sigla: 'SOSS', nome: 'Sossego' },
	    { sigla: 'TENO', nome: 'Tenório' },
	    { sigla: 'UUZ', nome: 'Umbuzeiro' },
	    { sigla: 'AMPA', nome: 'Amparo' },
	    { sigla: 'BRG', nome: 'Barra de São Miguel' },
	    { sigla: 'CCK', nome: 'Cabaceiras' },
	    { sigla: 'CMW', nome: 'Camalaú' },
	    { sigla: 'CRAU', nome: 'Caraúbas' },
	    { sigla: 'CXG', nome: 'Congo' },
	    { sigla: 'COXI', nome: 'Coxixola' },
	    { sigla: 'GRJ', nome: 'Gurjão' },
	    { sigla: 'LVR', nome: 'Livramento' },
	    { sigla: 'MER', nome: 'Monteiro' },
	    { sigla: 'OUV', nome: 'Ouro Velho' },
	    { sigla: 'PARR', nome: 'Parar I' },
	    { sigla: 'PRK', nome: 'Prata' },
	    { sigla: 'STND', nome: 'Santo André' },
	    { sigla: 'SDWM', nome: 'São Domingos do Cariri' },
	    { sigla: 'SCX', nome: 'São João do Cariri' },
	    { sigla: 'SXG', nome: 'São João do Tigre' },
	    { sigla: 'SXC', nome: 'São José dos Cordeiros' },
	    { sigla: 'SMZ', nome: 'São Sebastião do Umbuzeiro' },
	    { sigla: 'SRB', nome: 'Serra Branca' },
	    { sigla: 'SUE', nome: 'Sumé' },
	    { sigla: 'ZABE', nome: 'Zabelê' },
	    { sigla: 'ARBA', nome: 'Areia de Baraúnas' },
	    { sigla: 'ASSC', nome: 'Assunção' },
	    { sigla: 'BBZ', nome: 'Belém do Brejo do Cruz' },
	    { sigla: 'BMU', nome: 'Bom Sucesso' },
	    { sigla: 'BJZ', nome: 'Brejo do Cruz' },
	    { sigla: 'BOA', nome: 'Brejo dos Santos' },
	    { sigla: 'CKE', nome: 'Cacimba de Areia' },
	    { sigla: 'CIMS', nome: 'Cacimbas' },
	    { sigla: 'CAJA', nome: 'Cajazeirinhas' },
	    { sigla: 'CGY', nome: 'Catingueira' },
	    { sigla: 'CRH', nome: 'Catole do Rocha' },
	    { sigla: 'CDX', nome: 'Condado' },
	    { sigla: 'CES', nome: 'Coremas' },
	    { sigla: 'DST', nome: 'Desterro' },
	    { sigla: 'EMS', nome: 'Emas' },
	    { sigla: 'JCO', nome: 'Jericó' },
	    { sigla: 'JDO', nome: 'Junco do Seridó' },
	    { sigla: 'LAG', nome: 'Lagoa' },
	    { sigla: 'MEX', nome: 'Mãe D\'Água' },
	    { sigla: 'MLT', nome: 'Malta' },
	    { sigla: 'MGSS', nome: 'Mato Grosso' },
	    { sigla: 'MURE', nome: 'Matureia' },
	    { sigla: 'PSM', nome: 'Passagem' },
	    { sigla: 'POS', nome: 'Patos' },
	    { sigla: 'PUX', nome: 'Paulista' },
	    { sigla: 'PBL', nome: 'Pombal' },
	    { sigla: 'QXB', nome: 'Quixaba' },
	    { sigla: 'RHO', nome: 'Riacho dos Cavalos' },
	    { sigla: 'SKH', nome: 'Salgadinho' },
	    { sigla: 'SLZ', nome: 'Santa Luzia' },
	    { sigla: 'SYH', nome: 'Santa Teresinha' },
	    { sigla: 'SBTP', nome: 'São Bentinho' },
	    { sigla: 'SBT', nome: 'São Bento' },
	    { sigla: 'SDMP', nome: 'São Domingos de Pombal' },
	    { sigla: 'SJH', nome: 'São José de Espinharas' },
	    { sigla: 'SKF', nome: 'São José do Bonfim' },
	    { sigla: 'SBCZ', nome: 'São José do Brejo do Cruz' },
	    { sigla: 'SXS', nome: 'São José do Sabugi' },
	    { sigla: 'SAM', nome: 'São Mamede' },
	    { sigla: 'TER', nome: 'Taperoá' },
	    { sigla: 'TXE', nome: 'Teixeira' },
	    { sigla: 'VRA', nome: 'Várzea' },
	    { sigla: 'VASR', nome: 'Vista Serrana' },
	    { sigla: 'ABW', nome: 'Água Branca' },
	    { sigla: 'AGY', nome: 'Aguiar' },
	    { sigla: 'BVE', nome: 'Boa Ventura' },
	    { sigla: 'CCI', nome: 'Conceição' },
	    { sigla: 'CWV', nome: 'Curral Velho' },
	    { sigla: 'DIA', nome: 'Diamante' },
	    { sigla: 'IIW', nome: 'Ibiara' },
	    { sigla: 'IGRY', nome: 'Igaracy' },
	    { sigla: 'ILD', nome: 'Imaculada' },
	    { sigla: 'IRN', nome: 'Itaporanga' },
	    { sigla: 'JUX', nome: 'Juru' },
	    { sigla: 'MAN', nome: 'Manaíra' },
	    { sigla: 'NOD', nome: 'Nova Olinda' },
	    { sigla: 'OLH', nome: 'Olho D\'Água' },
	    { sigla: 'PKB', nome: 'Pedra Branca' },
	    { sigla: 'PIC', nome: 'Piancó' },
	    { sigla: 'PIL', nome: 'Princesa Isabel' },
	    { sigla: 'STNE', nome: 'Santa Inês' },
	    { sigla: 'SKT', nome: 'Santana de Mangueira' },
	    { sigla: 'SOW', nome: 'Santana dos Garrotes' },
	    { sigla: 'SKC', nome: 'São José de Caiana' },
	    { sigla: 'SWJP', nome: 'São José de Princesa' },
	    { sigla: 'SKE', nome: 'Serra Grande' },
	    { sigla: 'TVS', nome: 'Tavares' },
	    { sigla: 'APAR', nome: 'Aparecida' },
	    { sigla: 'BNBT', nome: 'Bernardino Batista' },
	    { sigla: 'BEU', nome: 'Bom Jesus' },
	    { sigla: 'BSF', nome: 'Bonito de Santa Fé' },
	    { sigla: 'CHY', nome: 'Cachoeira dos Índios' },
	    { sigla: 'CZS', nome: 'Cajazeiras' },
	    { sigla: 'CWE', nome: 'Carrapateira' },
	    { sigla: 'LSO', nome: 'Lastro' },
	    { sigla: 'MRIZ', nome: 'Marizópolis' },
	    { sigla: 'MHB', nome: 'Monte Horebe' },
	    { sigla: 'NZZ', nome: 'Nazarezinho' },
	    { sigla: 'PODA', nome: 'Poço Dantas' },
	    { sigla: 'POCO', nome: 'Poço de José de Moura' },
	    { sigla: 'SCZ', nome: 'Santa Cruz' },
	    { sigla: 'STH', nome: 'Santa Helena' },
	    { sigla: 'STAE', nome: 'Santarém' },
	    { sigla: 'SAFN', nome: 'São Francisco' },
	    { sigla: 'SXQ', nome: 'São João do Rio do Peixe' },
	    { sigla: 'SGP', nome: 'São José da Lagoa Tapada' },
	    { sigla: 'SPN', nome: 'São José de Piranhas' },
	    { sigla: 'SZA', nome: 'Sousa' },
	    { sigla: 'TRU', nome: 'Triunfo' },
	    { sigla: 'UIN', nome: 'Uiraúna' },
	    { sigla: 'VIEI', nome: 'Vieirópolis' }
	],

    'AL': [
	    { sigla: 'BNA', nome: 'Barra de Santo Antônio' },
	    { sigla: 'CQC', nome: 'Coqueiro Seco' },
	    { sigla: 'MCO', nome: 'Maceió' },
	    { sigla: 'MHD', nome: 'Marechal Deodoro' },
	    { sigla: 'MEA', nome: 'Messias' },
	    { sigla: 'PAPU', nome: 'Paripuueira' },
	    { sigla: 'PLR', nome: 'Pilar' },
	    { sigla: 'RGO', nome: 'Rio Largo' },
	    { sigla: 'SZT', nome: 'Santa Luzia do Norte' },
	    { sigla: 'SLQ', nome: 'São Luís do Quitunde' },
	    { sigla: 'STU', nome: 'Satuba' },
	    { sigla: 'BQH', nome: 'Branquinha' },
	    { sigla: 'CPEE', nome: 'Campestre' },
	    { sigla: 'COL', nome: 'Colônia Leopoldina' },
	    { sigla: 'FXS', nome: 'Flexeiras' },
	    { sigla: 'IBG', nome: 'Ibateguara' },
	    { sigla: 'JPE', nome: 'Jacuípe' },
	    { sigla: 'JPG', nome: 'Japaratinga' },
	    { sigla: 'JQG', nome: 'Joaquim Gomes' },
	    { sigla: 'JUD', nome: 'Jundiá' },
	    { sigla: 'MGI', nome: 'Maragogi' },
	    { sigla: 'MZC', nome: 'Matriz de Camaragibe' },
	    { sigla: 'MRI', nome: 'Murici' },
	    { sigla: 'NLO', nome: 'Novo Lino' },
	    { sigla: 'PEG', nome: 'Passo de Camaragibe' },
	    { sigla: 'PCV', nome: 'Porto Calvo' },
	    { sigla: 'POP', nome: 'Porto de Pedras' },
	    { sigla: 'SJJ', nome: 'São José da Laje' },
	    { sigla: 'SYM', nome: 'São Miguel dos Milagres' },
	    { sigla: 'UPS', nome: 'União dos Palmares' },
	    { sigla: 'AAD', nome: 'Anadia' },
	    { sigla: 'ATL', nome: 'Atalaia' },
	    { sigla: 'BDG', nome: 'Barra de São Miguel' },
	    { sigla: 'BOD', nome: 'Boca da Mata' },
	    { sigla: 'CJO', nome: 'Cajueiro' },
	    { sigla: 'CLR', nome: 'Campo Alegre' },
	    { sigla: 'CPA', nome: 'Capela' },
	    { sigla: 'CHK', nome: 'Chã Preta' },
	    { sigla: 'CUI', nome: 'Coruripe' },
	    { sigla: 'JQPA', nome: 'Jequiá da Praia' },
	    { sigla: 'MVM', nome: 'Mar Vermelho' },
	    { sigla: 'PJO', nome: 'Paulo Jacinto' },
	    { sigla: 'PYD', nome: 'Pindoba' },
	    { sigla: 'QGO', nome: 'Quebrangulo' },
	    { sigla: 'RTI', nome: 'Roteiro' },
	    { sigla: 'SUD', nome: 'Santana do Mundaú' },
	    { sigla: 'SMM', nome: 'São Miguel dos Campos' },
	    { sigla: 'VIS', nome: 'Viçosa' },
	    { sigla: 'BLX', nome: 'Belém' },
	    { sigla: 'CBH', nome: 'Cacimbinhas' },
	    { sigla: 'CYO', nome: 'Coité do Noia' },
	    { sigla: 'DSH', nome: 'Dois Riachos' },
	    { sigla: 'EAL', nome: 'Estrela de Alagoas' },
	    { sigla: 'ICY', nome: 'Igaci' },
	    { sigla: 'MJR', nome: 'Major Isidoro' },
	    { sigla: 'MBO', nome: 'Maribondo' },
	    { sigla: 'MNX', nome: 'Minador do Negão' },
	    { sigla: 'PIN', nome: 'Palmeira dos Índios' },
	    { sigla: 'TQD', nome: 'Tanque D\'Arca' },
	    { sigla: 'TAQ', nome: 'Taquarana' },
	    { sigla: 'AIR', nome: 'Arapiraca' },
	    { sigla: 'BTH', nome: 'Batalha' },
	    { sigla: 'BLN', nome: 'Belo Monte' },
	    { sigla: 'CGN', nome: 'Campo Grande' },
	    { sigla: 'KIS', nome: 'Craíbas' },
	    { sigla: 'FGE', nome: 'Feira Grande' },
	    { sigla: 'FZO', nome: 'Feliz Deserto' },
	    { sigla: 'GUP', nome: 'Girau do Ponciano' },
	    { sigla: 'IGJ', nome: 'Igreja Nova' },
	    { sigla: 'JAA', nome: 'Jaramataia' },
	    { sigla: 'JQO', nome: 'Junqueiro' },
	    { sigla: 'LDC', nome: 'Lagoa da Canoa' },
	    { sigla: 'LIM', nome: 'Limoeiro de Anadia' },
	    { sigla: 'OGG', nome: 'Olho D\'Água Grande' },
	    { sigla: 'PND', nome: 'Penedo' },
	    { sigla: 'PIB', nome: 'Piaçabuçu' },
	    { sigla: 'PLC', nome: 'Porto Real do Colégio' },
	    { sigla: 'SOB', nome: 'São Brás' },
	    { sigla: 'SWS', nome: 'São Sebastião' },
	    { sigla: 'TNVL', nome: 'Teotônio Vilela' },
	    { sigla: 'TRP', nome: 'Traipu' },
	    { sigla: 'CKN', nome: 'Carneiros' },
	    { sigla: 'JSH', nome: 'Jacaré dos Homens' },
	    { sigla: 'MVI', nome: 'Maravilha' },
	    { sigla: 'MON', nome: 'Monteirópolis' },
	    { sigla: 'OLF', nome: 'Olho D\'Água das Flores' },
	    { sigla: 'OIV', nome: 'Olivença' },
	    { sigla: 'OUB', nome: 'Ouro Branco' },
	    { sigla: 'PSY', nome: 'Palestina' },
	    { sigla: 'PKW', nome: 'Pão de Açúcar' },
	    { sigla: 'PCH', nome: 'Poço das Trincheiras' },
	    { sigla: 'SNN', nome: 'Santana do Ipanema' },
	    { sigla: 'SPX', nome: 'São José da Tapera' },
	    { sigla: 'SUP', nome: 'Senador Rui Palmeira' },
	    { sigla: 'ABN', nome: 'Água Branca' },
	    { sigla: 'CNK', nome: 'Canapi' },
	    { sigla: 'DGA', nome: 'Delmiro Gouveia' },
	    { sigla: 'IHP', nome: 'Inhapi' },
	    { sigla: 'MGR', nome: 'Mata Grande' },
	    { sigla: 'OHD', nome: 'Olho D\'Água do Casado' },
	    { sigla: 'PRCH', nome: 'Pariconha' },
	    { sigla: 'PYH', nome: 'Piranhas' }
	],

    'PE': [
        { sigla: 'SGI', nome: 'Salgueiro' },
        { sigla: 'VER', nome: 'Veredinha' },
	{ sigla: 'ACV', nome: 'ARCOVERDE' },
	{sigla: 'PTA', nome: 'PETROLINA'}    
	
    ],
    'PI': [
        { sigla: 'AOX', nome: 'Alto Longa' },
        { sigla: 'ZRA', nome: 'Zé Doca' },
	
    ],
    'BA': [
	    { sigla: 'CAR', nome: 'Camaçari' },
	    { sigla: 'CIS', nome: 'Candeias' },
	    { sigla: 'CAU', nome: 'Catu' },
	    { sigla: 'DSA', nome: 'Dias D\'Ávila' },
	    { sigla: 'IAP', nome: 'Itaparica' },
	    { sigla: 'LFS', nome: 'Lauro de Freitas' },
	    { sigla: 'MDY', nome: 'Madre de Deus' },
	    { sigla: 'MJO', nome: 'Mata de São João' },
	    { sigla: 'PJC', nome: 'Pojuca' },
	    { sigla: 'SDR', nome: 'Salvador' },
	    { sigla: 'SFN', nome: 'São Francisco do Conde' },
	    { sigla: 'SSE', nome: 'São Sebastião do Passe' },
	    { sigla: 'SMF', nome: 'Simões Filho' },
	    { sigla: 'VCZ', nome: 'Vera Cruz' },
	    { sigla: 'ALM', nome: 'Almadina' },
	    { sigla: 'ATW', nome: 'Arataca' },
	    { sigla: 'BPO', nome: 'Barro Preto' },
	    { sigla: 'BUE', nome: 'Buerarema' },
	    { sigla: 'COC', nome: 'Coaraci' },
	    { sigla: 'FMV', nome: 'Firmino Alves' },
	    { sigla: 'FAL', nome: 'Floresta Azul' },
	    { sigla: 'ICR', nome: 'Ibiracará' },
	    { sigla: 'IBC', nome: 'Ibicuí' },
	    { sigla: 'IUI', nome: 'Iguaí' },
	    { sigla: 'ILH', nome: 'Ilhéus' },
	    { sigla: 'ITB', nome: 'Itabuna' },
	    { sigla: 'IJL', nome: 'Itaju do Colônia' },
	    { sigla: 'IJP', nome: 'Itajuípe' },
	    { sigla: 'YPE', nome: 'Itapé' },
	    { sigla: 'ITT', nome: 'Itapitanga' },
	    { sigla: 'IRR', nome: 'Itororó' },
	    { sigla: 'JSI', nome: 'Jussari' },
	    { sigla: 'NCO', nome: 'Nova Canaã' },
	    { sigla: 'SVT', nome: 'Santa Cruz da Vitória' },
	    { sigla: 'SVQ', nome: 'São José da Vitória' },
	    { sigla: 'WNA', nome: 'Una' },
	    { sigla: 'UUU', nome: 'Uruçuca' },
	    { sigla: 'EUS', nome: 'Eunápolis' },
	    { sigla: 'GNG', nome: 'Guaratinga' },
	    { sigla: 'IBH', nome: 'Itabela' },
	    { sigla: 'IMM', nome: 'Itagimirim' },
	    { sigla: 'IEY', nome: 'Itapebi' },
	    { sigla: 'PGU', nome: 'Porto Seguro' },
	    { sigla: 'SZB', nome: 'Santa Cruz Cabrália' },
	    { sigla: 'ALC', nome: 'Alcobaça' },
	    { sigla: 'CRV', nome: 'Caravelas' },
	    { sigla: 'IBP', nome: 'Ibirapuã' },
	    { sigla: 'IMJ', nome: 'Itamaraju' },
	    { sigla: 'IHM', nome: 'Itanhém' },
	    { sigla: 'JUC', nome: 'Jucuruçu' },
	    { sigla: 'LED', nome: 'Lajedão' },
	    { sigla: 'MSN', nome: 'Medeiros Neto' },
	    { sigla: 'MUI', nome: 'Mucuri' },
	    { sigla: 'NVV', nome: 'Nova Viçosa' },
	    { sigla: 'PRD', nome: 'Prado' },
	    { sigla: 'TAF', nome: 'Teixeira de Freitas' },
	    { sigla: 'VEE', nome: 'Vereda' },
	    { sigla: 'BLE', nome: 'Belmonte' },
	    { sigla: 'CCN', nome: 'Camacan' },
	    { sigla: 'CVS', nome: 'Canavieiras' },
	    { sigla: 'IRM', nome: 'Itarantim' },
	    { sigla: 'MAE', nome: 'Mascote' },
	    { sigla: 'PSL', nome: 'Pau Brasil' },
	    { sigla: 'POG', nome: 'Potiraguá' },
	    { sigla: 'SUY', nome: 'Santa Luzia' },
	    { sigla: 'AEL', nome: 'Aurelino Leal' },
	    { sigla: 'BCH', nome: 'Barra do Rocha' },
	    { sigla: 'CMM', nome: 'Camamu' },
	    { sigla: 'GDU', nome: 'Gandu' },
	    { sigla: 'GGG', nome: 'Gongogi' },
	    { sigla: 'IIP', nome: 'Ibirapitanga' },
	    { sigla: 'IRT', nome: 'Ibirataia' },
	    { sigla: 'IGH', nome: 'Igrapiúna' },
	    { sigla: 'IRE', nome: 'Itacaré' },
	    { sigla: 'IMY', nome: 'Itamari' },
	    { sigla: 'IUR', nome: 'Itubera' },
	    { sigla: 'MRU', nome: 'Marau' },
	    { sigla: 'NIA', nome: 'Nilo Peçanha' },
	    { sigla: 'NIB', nome: 'Nova Ibia' },
	    { sigla: 'PDQ', nome: 'Piraí do Norte' },
	    { sigla: 'PTQ', nome: 'Presidente Tancredo Neves' },
	    { sigla: 'TEN', nome: 'Teolândia' },
	    { sigla: 'UIA', nome: 'Ubaitaba' },
	    { sigla: 'UAT', nome: 'Ubata' },
	    { sigla: 'WGS', nome: 'Wenceslau Guimarães' },
	    { sigla: 'AIQ', nome: 'Aiquara' },
	    { sigla: 'APE', nome: 'Apuarema' },
	    { sigla: 'CVO', nome: 'Cravolândia' },
	    { sigla: 'DMA', nome: 'Dário Meira' },
	    { sigla: 'IPW', nome: 'Ipiaú' },
	    { sigla: 'IRJ', nome: 'Irajuba' },
	    { sigla: 'YGI', nome: 'Itagi' },
	    { sigla: 'IGB', nome: 'Itagiba' },
	    { sigla: 'IQA', nome: 'Itaquara' },
	    { sigla: 'IIC', nome: 'Itiruçu' },
	    { sigla: 'JGQ', nome: 'Jaguaquara' },
	    { sigla: 'JEE', nome: 'Jequié' },
	    { sigla: 'JTN', nome: 'Jitaúna' },
	    { sigla: 'LFE', nome: 'Lafaete Coutinho' },
	    { sigla: 'LTL', nome: 'Lajedo do Tabocal' },
	    { sigla: 'MVO', nome: 'Manoel Vitorino' },
	    { sigla: 'MAS', nome: 'Maracás' },
	    { sigla: 'NOI', nome: 'Nova Itarana' },
	    { sigla: 'PLY', nome: 'Planaltino' },
	    { sigla: 'SAT', nome: 'Santa Inês' },
	    { sigla: 'BXD', nome: 'Baixa Grande' },
	    { sigla: 'CKX', nome: 'Caém' },
	    { sigla: 'CDG', nome: 'Caldeirão Grande' },
	    { sigla: 'CCG', nome: 'Capim Grosso' },
	    { sigla: 'JBN', nome: 'Jacobina' },
	    { sigla: 'MJU', nome: 'Macajuba' },
	    { sigla: 'MRY', nome: 'Mairi' },
	    { sigla: 'MGN', nome: 'Miguel Calmon' },
	    { sigla: 'MIN', nome: 'Mirangaba' },
	    { sigla: 'MHU', nome: 'Morro do Chapéu' },
	    { sigla: 'MNO', nome: 'Mundo Novo' },
	    { sigla: 'OUL', nome: 'Ourolândia' },
	    { sigla: 'PRI', nome: 'Piritiba' },
	    { sigla: 'PNF', nome: 'Ponto Novo' },
	    { sigla: 'QXR', nome: 'Quixabeira' },
	    { sigla: 'SUJ', nome: 'São José do Jacuípe' },
	    { sigla: 'SUX', nome: 'Saúde' },
	    { sigla: 'SEL', nome: 'Serrolândia' },
	    { sigla: 'TAP', nome: 'Tapiramutá' },
	    { sigla: 'VDA', nome: 'Várzea da Roça' },
	    { sigla: 'VZC', nome: 'Várzea do Poço' },
	    { sigla: 'VOA', nome: 'Várzea Nova' },
	    { sigla: 'AED', nome: 'América Dourada' },
	    { sigla: 'BDS', nome: 'Barra do Mendes' },
	    { sigla: 'BLT', nome: 'Barro Alto' },
	    { sigla: 'CFM', nome: 'Cafarnaum' },
	    { sigla: 'CNR', nome: 'Canarana' },
	    { sigla: 'CAL', nome: 'Central' },
	    { sigla: 'IBB', nome: 'Ibipetá' },
	    { sigla: 'IIY', nome: 'Ibititá' },
	    { sigla: 'IEE', nome: 'Irecê' },
	    { sigla: 'JDY', nome: 'João Dourado' },
	    { sigla: 'JSS', nome: 'Jussara' },
	    { sigla: 'LPO', nome: 'Lapão' },
	    { sigla: 'MUD', nome: 'Mulungu do Morro' },
	    { sigla: 'PDN', nome: 'Presidente Dutra' },
	    { sigla: 'SYK', nome: 'São Gabriel' },
	    { sigla: 'UII', nome: 'Uibaí' },
	    { sigla: 'BAA', nome: 'Barra' },
	    { sigla: 'GOU', nome: 'Gentio do Ouro' },
	    { sigla: 'IGD', nome: 'Itaguçu da Bahia' },
	    { sigla: 'XXQ', nome: 'Xique-Xique' },
	    { sigla: 'CSV', nome: 'Casa Nova' },
	    { sigla: 'CRX', nome: 'Curacá' },
	    { sigla: 'JUO', nome: 'Juazeiro' },
	    { sigla: 'SHB', nome: 'Sobradinho' },
	    { sigla: 'UAU', nome: 'Uauá' },
	    { sigla: 'ADK', nome: 'Andorinha' },
	    { sigla: 'AV S', nome: 'Antônio Gonçalves' },
	    { sigla: 'CFS', nome: 'Campo Formoso' },
	    { sigla: 'FDA', nome: 'Filadélfia' },
	    { sigla: 'IIB', nome: 'Itiúba' },
	    { sigla: 'JGA', nome: 'Jaguarari' },
	    { sigla: 'PDC', nome: 'Pindobaçu' },
	    { sigla: 'SBM', nome: 'Senhor do Bonfim' },
	    { sigla: 'UMS', nome: 'Umburanas' },
	    { sigla: 'CGR', nome: 'Campo Alegre de Lourdes' },
	    { sigla: 'PID', nome: 'Pilão Arcado' },
	    { sigla: 'REM', nome: 'Remanso' },
	    { sigla: 'SES', nome: 'Sento Sé' },
	    { sigla: 'AFA', nome: 'Água Fria' },
	    { sigla: 'ARG', nome: 'Amélia Rodrigues' },
	    { sigla: 'AEX', nome: 'Anguera' },
	    { sigla: 'ATC', nome: 'Antônio Cardoso' },
	    { sigla: 'CFA', nome: 'Conceição da Feira' },
	    { sigla: 'CJP', nome: 'Conceição do Jacuípe' },
	    { sigla: 'CEI', nome: 'Coração de Maria' },
	    { sigla: 'FSA', nome: 'Feira de Santana' },
	    { sigla: 'IEC', nome: 'Ipecaetá' },
	    { sigla: 'IRX', nome: 'Irará' },
	    { sigla: 'SNB', nome: 'Santa Bárbara' },
	    { sigla: 'SXA', nome: 'Santanópolis' },
	    { sigla: 'SNA', nome: 'Santo Amaro' },
	    { sigla: 'SEV', nome: 'Santo Estêvão' },
	    { sigla: 'SGC', nome: 'São Gonçalo dos Campos' },
	    { sigla: 'SUF', nome: 'Saubara' },
	    { sigla: 'SXX', nome: 'Serra Preta' },
	    { sigla: 'TQH', nome: 'Tanquinho' },
	    { sigla: 'TDS', nome: 'Teodoro Sampaio' },
	    { sigla: 'TNV', nome: 'Terra Nova' },
	    { sigla: 'ASN', nome: 'Adustina' },
	    { sigla: 'ANX', nome: 'Antas' },
	    { sigla: 'BZE', nome: 'Banzaê' },
	    { sigla: 'CDT', nome: 'Cícero Dantas' },
	    { sigla: 'CIP', nome: 'Cipó' },
	    { sigla: 'FIA', nome: 'Fátima' },
	    { sigla: 'HIS', nome: 'Heliópolis' },
	    { sigla: 'NVO', nome: 'Nova Soure' },
	    { sigla: 'NTF', nome: 'Novo Triunfo' },
	    { sigla: 'PGA', nome: 'Paripiranga' },
	    { sigla: 'RII', nome: 'Ribeira do Amparo' },
	    { sigla: 'RBP', nome: 'Ribeira do Pombal' },
	    { sigla: 'TCN', nome: 'Tucano' },
	    { sigla: 'CSO', nome: 'Cansanção' },
	    { sigla: 'CUS', nome: 'Canudos' },
	    { sigla: 'ECN', nome: 'Euclides da Cunha' },
	    { sigla: 'MEO', nome: 'Monte Santo' },
	    { sigla: 'QJG', nome: 'Quijingue' },
	    { sigla: 'AAC', nome: 'Araci' },
	    { sigla: 'BRKS', nome: 'Barrocas' },
	    { sigla: 'BIR', nome: 'Biritinga' },
	    { sigla: 'CNW', nome: 'Candeal' },
	    { sigla: 'CWG', nome: 'Capela do Alto Alegre' },
	    { sigla: 'CCC', nome: 'Conceição do Coité' },
	    { sigla: 'GVO', nome: 'Gavião' },
	    { sigla: 'ICH', nome: 'Ichu' },
	    { sigla: 'LAR', nome: 'Lamarão' },
	    { sigla: 'NTA', nome: 'Nordestina' },
	    { sigla: 'NFT', nome: 'Nova Fátima' },
	    { sigla: 'PPW', nome: 'Pedra Preta' },
	    { sigla: 'PNY', nome: 'Pintadas' },
	    { sigla: 'QES', nome: 'Queimadas' },
	    { sigla: 'RRD', nome: 'Retirolandia' },
	    { sigla: 'RJP', nome: 'Riachão do Jacuípe' },
	    { sigla: 'SUZ', nome: 'Santaluz' },
	    { sigla: 'SGQ', nome: 'São Domingos' },
	    { sigla: 'SEH', nome: 'Serrinha' },
	    { sigla: 'TOF', nome: 'Teofilândia' },
	    { sigla: 'VLE', nome: 'Valente' },
	    { sigla: 'ABE', nome: 'Abaré' },
	    { sigla: 'CKH', nome: 'Chorrochó' },
	    { sigla: 'CRJ', nome: 'Coronel João Sá' },
	    { sigla: 'GLO', nome: 'Glória' },
	    { sigla: 'JRO', nome: 'Jeremoabo' },
	    { sigla: 'MUX', nome: 'Macururé' },
	    { sigla: 'PAF', nome: 'Paulo Afonso' },
	    { sigla: 'PXD', nome: 'Pedro Alexandre' },
	    { sigla: 'RDE', nome: 'Rodelas' },
	    { sigla: 'SGY', nome: 'Santa Brígida' },
	    { sigla: 'SQI', nome: 'Sítio do Quinto' },
	    { sigla: 'BTM', nome: 'Boa Vista do Tupim' },
	    { sigla: 'BNK', nome: 'Bonito' },
	    { sigla: 'ICU', nome: 'Iacu' },
	    { sigla: 'IIQ', nome: 'Ibiquera' },
	    { sigla: 'IPI', nome: 'Ipirá' },
	    { sigla: 'IEB', nome: 'Itaberaba' },
	    { sigla: 'IEW', nome: 'Itaeté' },
	    { sigla: 'LEH', nome: 'Lajedinho' },
	    { sigla: 'MNZ', nome: 'Marcionílio Souza' },
	    { sigla: 'RYB', nome: 'Ruy Barbosa' },
	    { sigla: 'UTG', nome: 'Utinga' },
	    { sigla: 'WGR', nome: 'Wagner' },
	    { sigla: 'ANI', nome: 'Andaraí' },
	    { sigla: 'BOL', nome: 'Boninal' },
	    { sigla: 'IRQ', nome: 'Iraquara' },
	    { sigla: 'LCS', nome: 'Lençóis' },
	    { sigla: 'MCG', nome: 'Mucugê' },
	    { sigla: 'NVC', nome: 'Nova Redenção' },
	    { sigla: 'PLE', nome: 'Palmeiras' },
	    { sigla: 'SEB', nome: 'Seabra' },
	    { sigla: 'SUT', nome: 'Souto Soares' },
	    { sigla: 'AJB', nome: 'Acajutiba' },
	    { sigla: 'ALH', nome: 'Alagoinhas' },
	    { sigla: 'APR', nome: 'Aporá' },
	    { sigla: 'ACK', nome: 'Aracas' },
	    { sigla: 'AAM', nome: 'Aramari' },
	    { sigla: 'CSW', nome: 'Cardeal da Silva' },
	    { sigla: 'CNX', nome: 'Conde' },
	    { sigla: 'ERS', nome: 'Entre Rios' },
	    { sigla: 'ESA', nome: 'Esplanada' },
	    { sigla: 'IHU', nome: 'Inhambupe' },
	    { sigla: 'INR', nome: 'Itanagra' },
	    { sigla: 'OUG', nome: 'Ouricangas' },
	    { sigla: 'PEK', nome: 'Pedrão' },
	    { sigla: 'STK', nome: 'Sátiro Dias' },
	    { sigla: 'CSK', nome: 'Crisópolis' },
	    { sigla: 'IUW', nome: 'Itapicuru' },
	    { sigla: 'JDI', nome: 'Jandaíra' },
	    { sigla: 'ONN', nome: 'Olindina' },
	    { sigla: 'ROL', nome: 'Rio Real' },
	    { sigla: 'CPQ', nome: 'Cabaceiras do Paraguaçu' },
	    { sigla: 'CHE', nome: 'Cachoeira' },
	    { sigla: 'CAV', nome: 'Castro Alves' },
	    { sigla: 'CZM', nome: 'Cruz das Almas' },
	    { sigla: 'GMG', nome: 'Governador Mangabeira' },
	    { sigla: 'ITF', nome: 'Itatim' },
	    { sigla: 'MGP', nome: 'Maragogipe' },
	    { sigla: 'MLG', nome: 'Milagres' },
	    { sigla: 'MTI', nome: 'Muritiba' },
	    { sigla: 'RLO', nome: 'Rafael Jambeiro' },
	    { sigla: 'SYN', nome: 'Santa Teresinha' },
	    { sigla: 'SFX', nome: 'São Félix' },
	    { sigla: 'SEU', nome: 'Sapeaçu' },
	    { sigla: 'ARA', nome: 'Amargosa' },
	    { sigla: 'AUP', nome: 'Aratuípe' },
	    { sigla: 'BJX', nome: 'Brejões' },
	    { sigla: 'CIU', nome: 'Cairu' },
	    { sigla: 'CDL', nome: 'Conceição do Almeida' },
	    { sigla: 'DDC', nome: 'Dom Macedo Costa' },
	    { sigla: 'EMD', nome: 'Elísio Medrado' },
	    { sigla: 'JUP', nome: 'Jaguaribe' },
	    { sigla: 'JIQ', nome: 'Jiquiriçá' },
	    { sigla: 'LAJ', nome: 'Laje' },
	    { sigla: 'MIZ', nome: 'Muniz Ferreira' },
	    { sigla: 'MUU', nome: 'Mutuípe' },
	    { sigla: 'NAE', nome: 'Nazaré' },
	    { sigla: 'SAD', nome: 'Salinas da Margarida' },
	    { sigla: 'SNJ', nome: 'Santo Antônio de Jesus' },
	    { sigla: 'SFE', nome: 'São Felipe' },
	    { sigla: 'SYG', nome: 'São Miguel das Matas' },
	    { sigla: 'TOA', nome: 'Taperoá' },
	    { sigla: 'UBR', nome: 'Ubaíra' },
	    { sigla: 'VEC', nome: 'Valença' },
	    { sigla: 'VZO', nome: 'Varzedo' },
	    { sigla: 'CTB', nome: 'Caatiba' },
	    { sigla: 'IAM', nome: 'Itambé' },
	    { sigla: 'ING', nome: 'Itapetinga' },
	    { sigla: 'MCR', nome: 'Macarani' },
	    { sigla: 'MQQ', nome: 'Maiquinique' },
	    { sigla: 'AAE', nome: 'Anagé' },
	    { sigla: 'BHO', nome: 'Barra do Choça' },
	    { sigla: 'BLP', nome: 'Belo Campo' },
	    { sigla: 'BOV', nome: 'Boa Nova' },
	    { sigla: 'BJD', nome: 'Bom Jesus da Serra' },
	    { sigla: 'CTC', nome: 'Caetanos' },
	    { sigla: 'CDS', nome: 'Cândido Sales' },
	    { sigla: 'CIZ', nome: 'Caraíbas' },
	    { sigla: 'EZL', nome: 'Encruzilhada' },
	    { sigla: 'MRQ', nome: 'Mirante' },
	    { sigla: 'PNL', nome: 'Planalto' },
	    { sigla: 'PCE', nome: 'Poções' },
	    { sigla: 'RLR', nome: 'Ribeirão do Largo' },
	    { sigla: 'TEL', nome: 'Tremedal' },
	    { sigla: 'VCA', nome: 'Vitória da Conquista' },
	    { sigla: 'ABR', nome: 'Abaíra' },
	    { sigla: 'BAV', nome: 'Barra da Estiva' },
	    { sigla: 'CDC', nome: 'Contendas do Sincorá' },
	    { sigla: 'IIO', nome: 'Ibicoara' },
	    { sigla: 'IMX', nome: 'Iramaia' },
	    { sigla: 'ICX', nome: 'Ituaçu' },
	    { sigla: 'JSE', nome: 'Jussiape' },
	    { sigla: 'PYT', nome: 'Piata' },
	    { sigla: 'THU', nome: 'Tanhaçu' },
	    { sigla: 'CCE', nome: 'Caculé' },
	    { sigla: 'CEU', nome: 'Condeúba' },
	    { sigla: 'CWS', nome: 'Cordeiros' },
	    { sigla: 'GEU', nome: 'Guaíru' },
	    { sigla: 'ISC', nome: 'Ibiassucê' },
	    { sigla: 'JCC', nome: 'Jacaraci' },
	    { sigla: 'LID', nome: 'Licínio de Almeida' },
	    { sigla: 'MAY', nome: 'Maetinga' },
	    { sigla: 'MTG', nome: 'Mortugaba' },
	    { sigla: 'PPK', nome: 'Piripá' },
	    { sigla: 'PJQ', nome: 'Presidente Jânio Quadros' },
	    { sigla: 'UDI', nome: 'Urandi' },
	    { sigla: 'AAW', nome: 'Aracatu' },
	    { sigla: 'BRM', nome: 'Brumado' },
	    { sigla: 'DBL', nome: 'Dom Basílio' },
	    { sigla: 'LVB', nome: 'Livramento de Nossa Senhora' },
	    { sigla: 'MDD', nome: 'Malhada de Pedras' },
	    { sigla: 'RIT', nome: 'Rio do Antônio' },
	    { sigla: 'BMP', nome: 'Bom Jesus da Lapa' },
	    { sigla: 'MTW', nome: 'Matina' },
	    { sigla: 'RHS', nome: 'Riachão de Santana' },
	    { sigla: 'SHF', nome: 'Serra do Ramalho' },
	    { sigla: 'SOQ', nome: 'Sítio do Mato' },
	    { sigla: 'CTT', nome: 'Caetité' },
	    { sigla: 'CDY', nome: 'Candiba' },
	    { sigla: 'GNB', nome: 'Guanambi' },
	    { sigla: 'IGO', nome: 'Igaporã' },
	    { sigla: 'LRL', nome: 'Lagoa Real' },
	    { sigla: 'PSD', nome: 'Palmas de Monte Alto' },
	    { sigla: 'PDY', nome: 'Pindai' },
	    { sigla: 'SLJ', nome: 'Sebastião Laranjeiras' },
	    { sigla: 'BQA', nome: 'Boquira' },
	    { sigla: 'BSC', nome: 'Brotas de Macaúbas' },
	    { sigla: 'IIT', nome: 'Ibititanga' },
	    { sigla: 'IRK', nome: 'Ibitiara' },
	    { sigla: 'IBM', nome: 'Ibotirama' },
	    { sigla: 'IIX', nome: 'Ipupiara' },
	    { sigla: 'MCB', nome: 'Macaúbas' },
	    { sigla: 'MRP', nome: 'Morpará' },
	    { sigla: 'MSF', nome: 'Muquém de São Francisco' },
	    { sigla: 'NHZ', nome: 'Novo Horizonte' },
	    { sigla: 'OJH', nome: 'Oliveira dos Brejinhos' },
	    { sigla: 'PRN', nome: 'Paratinga' },
	    { sigla: 'CPK', nome: 'Canápolis' },
	    { sigla: 'CYB', nome: 'Coribe' },
	    { sigla: 'CTI', nome: 'Correntina' },
	    { sigla: 'JBI', nome: 'Jaborandi' },
	    { sigla: 'SMV', nome: 'Santa Maria da Vitória' },
	    { sigla: 'SNT', nome: 'Santana' },
	    { sigla: 'SFQ', nome: 'São Félix do Coribe' },
	    { sigla: 'SDW', nome: 'Serra Dourada' },
	    { sigla: 'CIN', nome: 'Carinhanha' },
	    { sigla: 'COX', nome: 'Cocos' },
	    { sigla: 'FDM', nome: 'Feira da Mata' },
	    { sigla: 'IIJ', nome: 'Iuiu' },
	    { sigla: 'MLH', nome: 'Malhada' },
	    { sigla: 'BUR', nome: 'Botuporã' },
	    { sigla: 'CTF', nome: 'Caturama' },
	    { sigla: 'ERCD', nome: 'Érico Cardoso' },
	    { sigla: 'PMI', nome: 'Paramirim' },
	    { sigla: 'ROC', nome: 'Rio de Contas' },
	    { sigla: 'ROR', nome: 'Rio do Pires' },
	    { sigla: 'TQO', nome: 'Tanque Novo' },
	    { sigla: 'ANL', nome: 'Angical' },
	    { sigla: 'BPL', nome: 'Baianópolis' },
	    { sigla: 'BES', nome: 'Barreiras' },
	    { sigla: 'BJL', nome: 'Brejolândia' },
	    { sigla: 'CKY', nome: 'Catolândia' },
	    { sigla: 'CGP', nome: 'Cotegipe' },
	    { sigla: 'CKT', nome: 'Cristópolis' },
	    { sigla: 'MIOO', nome: 'Luís Eduardo Magalhães' },
	    { sigla: 'RHV', nome: 'Riachão das Neves' },
	    { sigla: 'SSR', nome: 'São Desidério' },
	    { sigla: 'TBV', nome: 'Tabocas do Brejo Velho' },
	    { sigla: 'VNY', nome: 'Wanderley' },
	    { sigla: 'BIA', nome: 'Buritirama' },
	    { sigla: 'FRP', nome: 'Formosa do Rio Preto' },
	    { sigla: 'MMD', nome: 'Mansidão' },
	    { sigla: 'SRC', nome: 'Santa Rita de Cássia' }
    ],
    'SE': [
        { sigla: 'AJU', nome: 'Aracaju' },
        { sigla: 'SDS', nome: 'Simão Dias' }
    ],
    'MA': [
        { sigla: 'ALN', nome: 'Alcântara' },
        { sigla: 'VGE', nome: 'Vitória do Mearim' }
    ]
};

// Função para filtrar cidades com base no estado selecionado
function filtrarCidades() {
    const estadoSelecionado = document.getElementById('estado').value;
    const cidadeSelect = document.getElementById('cidade');

    // Limpa as opções de cidade
    cidadeSelect.innerHTML = '<option value="">Selecione uma cidade</option>';

    // Popula as cidades relacionadas ao estado selecionado
    if (estadoSelecionado && cidadesPorEstado[estadoSelecionado]) {
        cidadesPorEstado[estadoSelecionado].forEach(cidade => {
            const option = document.createElement('option');
            option.value = cidade.sigla;
            option.textContent = cidade.nome;
            cidadeSelect.appendChild(option);
        });
    }
}

// Função para gerar os títulos
function gerarTitulos() {
    const categoria = document.getElementById("categoria").value;
    const servico = document.getElementById("servico").value;
    const cnpj = document.getElementById("cnpj").value;
    const contrato = document.getElementById("contrato").value;
    const ponto = document.getElementById("ponto").value;
    const estado = document.getElementById("estado").value;
    const cidade = document.getElementById("cidade").value;
    const empresa = document.getElementById("empresa").value;

    const projetoPai = `${categoria}-${servico}-${cnpj}-${estado}-${empresa}`;
    const projetoFilho = `${categoria}-${servico}-${contrato}-${ponto}-${cidade}-${empresa}`;
    document.getElementById("projetoPai").innerText = projetoPai;
    document.getElementById("projetoFilho").innerText = projetoFilho;

    document.getElementById("resultModal").style.display = "flex"; // Exibe o modal
}

// Função para copiar textos
function copiarTexto(id) {
    const texto = document.getElementById(id).innerText;
    navigator.clipboard.writeText(texto).then(() => {
        alert("Texto copiado com sucesso!");
    });
}

// Função para fechar o modal
function fecharModal() {
    document.getElementById("resultModal").style.display = "none"; // Oculta o modal
}

