const cidadesPorEstado = {
    'CE': [
	    { sigla: 'AQZ', nome: 'Aquiraz' },
	    { sigla: 'BBB', nome: 'Beberibe' },
	    { sigla: 'CVL', nome: 'Cascavel' },
	    { sigla: 'CUC', nome: 'Caucaia' },
	    { sigla: 'CZH', nome: 'Chorozinho' },
	    { sigla: 'ESB', nome: 'Eusebio' },
	    { sigla: 'FLA', nome: 'Fortaleza' },
	    { sigla: 'GBA', nome: 'Guaiuba' },
	    { sigla: 'HZT', nome: 'Horizonte' },
	    { sigla: 'IAGA', nome: 'Itaitinga' },
	    { sigla: 'MCW', nome: 'Maracanaú' },
	    { sigla: 'MUE', nome: 'Maranguape' },
	    { sigla: 'PJS', nome: 'Pacajus' },
	    { sigla: 'PUB', nome: 'Pacatuba' },
	    { sigla: 'PDJ', nome: 'Pindoretama' },
	    { sigla: 'SGA', nome: 'São Gonçalo do Amarante' },
	    { sigla: 'ACP', nome: 'Acarape' },
	    { sigla: 'AUS', nome: 'Apuiarés' },
	    { sigla: 'AAB', nome: 'Acaroia' },
	    { sigla: 'ATU', nome: 'Aratuba' },
	    { sigla: 'BRK', nome: 'Barreira' },
	    { sigla: 'BTT', nome: 'Baturité' },
	    { sigla: 'CIE', nome: 'Canindé' },
	    { sigla: 'CSR', nome: 'Capistrano' },
	    { sigla: 'CID', nome: 'Caridade' },
	    { sigla: 'GNL', nome: 'General Sampaio' },
	    { sigla: 'GAG', nome: 'Guaramiranga' },
	    { sigla: 'MUN', nome: 'Mulungu' },
	    { sigla: 'OCR', nome: 'Ocara' },
	    { sigla: 'PTY', nome: 'Pacoti' },
	    { sigla: 'PMC', nome: 'Palmácia' },
	    { sigla: 'POY', nome: 'Paramoti' },
	    { sigla: 'RDC', nome: 'Redenção' },
	    { sigla: 'IGE', nome: 'Itapagé' },
	    { sigla: 'PUU', nome: 'Paracuru' },
	    { sigla: 'PWB', nome: 'Paraipaba' },
	    { sigla: 'POE', nome: 'Pentecoste' },
	    { sigla: 'SRU', nome: 'São Luís do Curu' },
	    { sigla: 'TJU', nome: 'Tejuçuoca' },
	    { sigla: 'TRY', nome: 'Trairi' },
	    { sigla: 'TUK', nome: 'Tururu' },
	    { sigla: 'URM', nome: 'Umirim' },
	    { sigla: 'UUA', nome: 'Uruburetama' },
	    { sigla: 'ATO', nome: 'Alto Santo' },
	    { sigla: 'ACA', nome: 'Aracati' },
	    { sigla: 'FORT', nome: 'Fortim' },
	    { sigla: 'ICN', nome: 'Ibicuitinga' },
	    { sigla: 'ICP', nome: 'Icapuí' },
	    { sigla: 'ICA', nome: 'Iracema' },
	    { sigla: 'IAX', nome: 'Itaicaba' },
	    { sigla: 'JGN', nome: 'Jaguaruana' },
	    { sigla: 'LNT', nome: 'Limoeiro do Norte' },
	    { sigla: 'MVA', nome: 'Morada Nova' },
	    { sigla: 'PHN', nome: 'Palhano' },
	    { sigla: 'PTZ', nome: 'Potiretama' },
	    { sigla: 'QXE', nome: 'Quixeré' },
	    { sigla: 'RUS', nome: 'Russas' },
	    { sigla: 'SUB', nome: 'São João do Jaguaribe' },
	    { sigla: 'TNT', nome: 'Tabuleiro do Norte' },
	    { sigla: 'ABY', nome: 'Abaiara' },
	    { sigla: 'AUR', nome: 'Aurora' },
	    { sigla: 'BBH', nome: 'Barbalha' },
	    { sigla: 'BAO', nome: 'Barro' },
	    { sigla: 'BJS', nome: 'Brejo Santo' },
	    { sigla: 'CAC', nome: 'Caririaçu' },
	    { sigla: 'CTO', nome: 'Crato' },
	    { sigla: 'GJO', nome: 'Granjeiro' },
	    { sigla: 'JDM', nome: 'Jardim' },
	    { sigla: 'JAT', nome: 'Jati' },
	    { sigla: 'JNE', nome: 'Juazeiro do Norte' },
	    { sigla: 'MRT', nome: 'Mauriti' },
	    { sigla: 'MGS', nome: 'Milagres' },
	    { sigla: 'MAH', nome: 'Missão Velha' },
	    { sigla: 'PFT', nome: 'Penaforte' },
	    { sigla: 'PTX', nome: 'Porteiras' },
	    { sigla: 'VZG', nome: 'Várzea Alegre' },
	    { sigla: 'AIB', nome: 'Aiuaba' },
	    { sigla: 'ANY', nome: 'Altaneira' },
	    { sigla: 'ANE', nome: 'Antonina do Norte' },
	    { sigla: 'ARP', nome: 'Araripe' },
	    { sigla: 'ASE', nome: 'Assaré' },
	    { sigla: 'CMS', nome: 'Campos Sales' },
	    { sigla: 'FBO', nome: 'Farias Brito' },
	    { sigla: 'NID', nome: 'Nova Olinda' },
	    { sigla: 'PGY', nome: 'Potengi' },
	    { sigla: 'SIQ', nome: 'Salitre' },
	    { sigla: 'SCI', nome: 'Santana do Cariri' },
	    { sigla: 'TRR', nome: 'Tarrafas' },
	    { sigla: 'ACX', nome: 'Alcântaras' },
	    { sigla: 'AOW', nome: 'Amontada' },
	    { sigla: 'CIW', nome: 'Carire' },
	    { sigla: 'CATN', nome: 'Catunda' },
	    { sigla: 'CEA', nome: 'Coreau' },
	    { sigla: 'FRQ', nome: 'Forquilha' },
	    { sigla: 'GRO', nome: 'Groairas' },
	    { sigla: 'HDA', nome: 'Hidrolândia' },
	    { sigla: 'ICB', nome: 'Irauçuba' },
	    { sigla: 'IOP', nome: 'Itapipoca' },
	    { sigla: 'MSS', nome: 'Massapê' },
	    { sigla: 'MEU', nome: 'Meruoca' },
	    { sigla: 'MIK', nome: 'Miraíma' },
	    { sigla: 'MUJ', nome: 'Moraújo' },
	    { sigla: 'RRB', nome: 'Reriutaba' },
	    { sigla: 'SNQ', nome: 'Santa Quitéria' },
	    { sigla: 'SAU', nome: 'Santana do Acaraú' },
	    { sigla: 'SOL', nome: 'Sobral' },
	    { sigla: 'VJT', nome: 'Varjota' },
	    { sigla: 'CUB', nome: 'Carnaubal' },
	    { sigla: 'COZ', nome: 'Croatá' },
	    { sigla: 'FHH', nome: 'Frecheirinha' },
	    { sigla: 'GCA', nome: 'Graça' },
	    { sigla: 'GRN', nome: 'Guaraciaba do Norte' },
	    { sigla: 'INX', nome: 'Ibiapina' },
	    { sigla: 'MUM', nome: 'Mucambo' },
	    { sigla: 'PUJ', nome: 'Pacujá' },
	    { sigla: 'SBN', nome: 'São Benedito' },
	    { sigla: 'TIG', nome: 'Tianguá' },
	    { sigla: 'UBJ', nome: 'Ubajara' },
	    { sigla: 'VCC', nome: 'Viçosa do Ceará' },
	    { sigla: 'AAU', nome: 'Acaraú' },
	    { sigla: 'BQN', nome: 'Barroquinha' },
	    { sigla: 'BCZ', nome: 'Bela Cruz' },
	    { sigla: 'CCM', nome: 'Camocim' },
	    { sigla: 'CHA', nome: 'Chaval' },
	    { sigla: 'CZW', nome: 'Cruz' },
	    { sigla: 'GNJ', nome: 'Granja' },
	    { sigla: 'IMW', nome: 'Itarema' },
	    { sigla: 'JIJO', nome: 'Jijoca de Jericoacoara' },
	    { sigla: 'MAC', nome: 'Marco' },
	    { sigla: 'MOP', nome: 'Martinópole' },
	    { sigla: 'MNH', nome: 'Morrinhos' },
	    { sigla: 'SNR', nome: 'Senador Sá' },
	    { sigla: 'UUO', nome: 'Uruoca' },
	    { sigla: 'ACR', nome: 'Acopiara' },
	    { sigla: 'CYS', nome: 'Cariús' },
	    { sigla: 'CYN', nome: 'Catarina' },
	    { sigla: 'IAU', nome: 'Iguatu' },
	    { sigla: 'JAS', nome: 'Jucás' },
	    { sigla: 'MBC', nome: 'Mombaça' },
	    { sigla: 'PDB', nome: 'Pedra Branca' },
	    { sigla: 'PQT', nome: 'Piquet Carneiro' },
	    { sigla: 'QXO', nome: 'Quixelô' },
	    { sigla: 'SOI', nome: 'Saboeiro' },
	    { sigla: 'BXO', nome: 'Baixio' },
	    { sigla: 'CED', nome: 'Cedro' },
	    { sigla: 'DPIP', nome: 'Deputado Irapuan Pinheiro' },
	    { sigla: 'ERR', nome: 'Ererê' },
	    { sigla: 'ICO', nome: 'Ico' },
	    { sigla: 'IMI', nome: 'Ipaumirim' },
	    { sigla: 'JAG', nome: 'Jaguaratama' },
	    { sigla: 'JGB', nome: 'Jaguaribara' },
	    { sigla: 'JGE', nome: 'Jaguaribe' },
	    { sigla: 'LVM', nome: 'Lavras da Mangabeira' },
	    { sigla: 'MHW', nome: 'Milha' },
	    { sigla: 'OOS', nome: 'Orós' },
	    { sigla: 'PEO', nome: 'Pereiro' },
	    { sigla: 'SOP', nome: 'Solonópole' },
	    { sigla: 'UMI', nome: 'Umari' },
	    { sigla: 'CTS', nome: 'Crateús' },
	    { sigla: 'IDA', nome: 'Independência' },
	    { sigla: 'NOE', nome: 'Novo Oriente' },
	    { sigla: 'QTS', nome: 'Quiterianópolis' },
	    { sigla: 'ARAE', nome: 'Ararendá' },
	    { sigla: 'IPZ', nome: 'Ipaporanga' },
	    { sigla: 'IPU', nome: 'Ipu' },
	    { sigla: 'IUE', nome: 'Ipueiras' },
	    { sigla: 'MHT', nome: 'Monsenhor Tabosa' },
	    { sigla: 'NRU', nome: 'Nova Russas' },
	    { sigla: 'PSF', nome: 'Pires Ferreira' },
	    { sigla: 'PGX', nome: 'Poranga' },
	    { sigla: 'TBL', nome: 'Tamboril' },
	    { sigla: 'AEZ', nome: 'Arneiroz' },
	    { sigla: 'PBU', nome: 'Parambu' },
	    { sigla: 'TUA', nome: 'Tauá' },
	    { sigla: 'BIU', nome: 'Banabuiú' },
	    { sigla: 'BVG', nome: 'Boa Viagem' },
	    { sigla: 'CHOO', nome: 'Choro' },
	    { sigla: 'IBW', nome: 'Ibaetama' },
	    { sigla: 'ITN', nome: 'Itapiúna' },
	    { sigla: 'ITK', nome: 'Itatira' },
	    { sigla: 'MDX', nome: 'Madalena' },
	    { sigla: 'QXA', nome: 'Quixadá' },
	    { sigla: 'QXM', nome: 'Quixeramobim' },
	    { sigla: 'SPM', nome: 'Senador Pompeu' }
    ],
    'RN': [
        { sigla: 'ARE', nome: 'Ares' },
        { sigla: 'UNM', nome: 'Upanema' },
        { sigla: 'VAVR', nome: 'Venha-Ver' },
        { sigla: 'VIO', nome: 'Viçosa' }
    ],
    'PB': [
        { sigla: 'AHD', nome: 'Alhandra' },
        { sigla: 'UIN', nome: 'Uiraúna' },
        { sigla: 'VIEI', nome: 'Vieirópolis' }
    ],
    'AL': [
	    { sigla: 'BNA', nome: 'Barra de Santo Antônio' },
	    { sigla: 'CQC', nome: 'Coqueiro Seco' },
	    { sigla: 'MCO', nome: 'Maceió' },
	    { sigla: 'MHD', nome: 'Marechal Deodoro' },
	    { sigla: 'MEA', nome: 'Messias' },
	    { sigla: 'PAPU', nome: 'Paripuueira' },
	    { sigla: 'PLR', nome: 'Pilar' },
	    { sigla: 'RGO', nome: 'Rio Largo' },
	    { sigla: 'SZT', nome: 'Santa Luzia do Norte' },
	    { sigla: 'SLQ', nome: 'São Luís do Quitunde' },
	    { sigla: 'STU', nome: 'Satuba' },
	    { sigla: 'BQH', nome: 'Branquinha' },
	    { sigla: 'CPEE', nome: 'Campestre' },
	    { sigla: 'COL', nome: 'Colônia Leopoldina' },
	    { sigla: 'FXS', nome: 'Flexeiras' },
	    { sigla: 'IBG', nome: 'Ibateguara' },
	    { sigla: 'JPE', nome: 'Jacuípe' },
	    { sigla: 'JPG', nome: 'Japaratinga' },
	    { sigla: 'JQG', nome: 'Joaquim Gomes' },
	    { sigla: 'JUD', nome: 'Jundiá' },
	    { sigla: 'MGI', nome: 'Maragogi' },
	    { sigla: 'MZC', nome: 'Matriz de Camaragibe' },
	    { sigla: 'MRI', nome: 'Murici' },
	    { sigla: 'NLO', nome: 'Novo Lino' },
	    { sigla: 'PEG', nome: 'Passo de Camaragibe' },
	    { sigla: 'PCV', nome: 'Porto Calvo' },
	    { sigla: 'POP', nome: 'Porto de Pedras' },
	    { sigla: 'SJJ', nome: 'São José da Laje' },
	    { sigla: 'SYM', nome: 'São Miguel dos Milagres' },
	    { sigla: 'UPS', nome: 'União dos Palmares' },
	    { sigla: 'AAD', nome: 'Anadia' },
	    { sigla: 'ATL', nome: 'Atalaia' },
	    { sigla: 'BDG', nome: 'Barra de São Miguel' },
	    { sigla: 'BOD', nome: 'Boca da Mata' },
	    { sigla: 'CJO', nome: 'Cajueiro' },
	    { sigla: 'CLR', nome: 'Campo Alegre' },
	    { sigla: 'CPA', nome: 'Capela' },
	    { sigla: 'CHK', nome: 'Chã Preta' },
	    { sigla: 'CUI', nome: 'Coruripe' },
	    { sigla: 'JQPA', nome: 'Jequiá da Praia' },
	    { sigla: 'MVM', nome: 'Mar Vermelho' },
	    { sigla: 'PJO', nome: 'Paulo Jacinto' },
	    { sigla: 'PYD', nome: 'Pindoba' },
	    { sigla: 'QGO', nome: 'Quebrangulo' },
	    { sigla: 'RTI', nome: 'Roteiro' },
	    { sigla: 'SUD', nome: 'Santana do Mundaú' },
	    { sigla: 'SMM', nome: 'São Miguel dos Campos' },
	    { sigla: 'VIS', nome: 'Viçosa' },
	    { sigla: 'BLX', nome: 'Belém' },
	    { sigla: 'CBH', nome: 'Cacimbinhas' },
	    { sigla: 'CYO', nome: 'Coité do Noia' },
	    { sigla: 'DSH', nome: 'Dois Riachos' },
	    { sigla: 'EAL', nome: 'Estrela de Alagoas' },
	    { sigla: 'ICY', nome: 'Igaci' },
	    { sigla: 'MJR', nome: 'Major Isidoro' },
	    { sigla: 'MBO', nome: 'Maribondo' },
	    { sigla: 'MNX', nome: 'Minador do Negão' },
	    { sigla: 'PIN', nome: 'Palmeira dos Índios' },
	    { sigla: 'TQD', nome: 'Tanque D\'Arca' },
	    { sigla: 'TAQ', nome: 'Taquarana' },
	    { sigla: 'AIR', nome: 'Arapiraca' },
	    { sigla: 'BTH', nome: 'Batalha' },
	    { sigla: 'BLN', nome: 'Belo Monte' },
	    { sigla: 'CGN', nome: 'Campo Grande' },
	    { sigla: 'KIS', nome: 'Craíbas' },
	    { sigla: 'FGE', nome: 'Feira Grande' },
	    { sigla: 'FZO', nome: 'Feliz Deserto' },
	    { sigla: 'GUP', nome: 'Girau do Ponciano' },
	    { sigla: 'IGJ', nome: 'Igreja Nova' },
	    { sigla: 'JAA', nome: 'Jaramataia' },
	    { sigla: 'JQO', nome: 'Junqueiro' },
	    { sigla: 'LDC', nome: 'Lagoa da Canoa' },
	    { sigla: 'LIM', nome: 'Limoeiro de Anadia' },
	    { sigla: 'OGG', nome: 'Olho D\'Água Grande' },
	    { sigla: 'PND', nome: 'Penedo' },
	    { sigla: 'PIB', nome: 'Piaçabuçu' },
	    { sigla: 'PLC', nome: 'Porto Real do Colégio' },
	    { sigla: 'SOB', nome: 'São Brás' },
	    { sigla: 'SWS', nome: 'São Sebastião' },
	    { sigla: 'TNVL', nome: 'Teotônio Vilela' },
	    { sigla: 'TRP', nome: 'Traipu' },
	    { sigla: 'CKN', nome: 'Carneiros' },
	    { sigla: 'JSH', nome: 'Jacaré dos Homens' },
	    { sigla: 'MVI', nome: 'Maravilha' },
	    { sigla: 'MON', nome: 'Monteirópolis' },
	    { sigla: 'OLF', nome: 'Olho D\'Água das Flores' },
	    { sigla: 'OIV', nome: 'Olivença' },
	    { sigla: 'OUB', nome: 'Ouro Branco' },
	    { sigla: 'PSY', nome: 'Palestina' },
	    { sigla: 'PKW', nome: 'Pão de Açúcar' },
	    { sigla: 'PCH', nome: 'Poço das Trincheiras' },
	    { sigla: 'SNN', nome: 'Santana do Ipanema' },
	    { sigla: 'SPX', nome: 'São José da Tapera' },
	    { sigla: 'SUP', nome: 'Senador Rui Palmeira' },
	    { sigla: 'ABN', nome: 'Água Branca' },
	    { sigla: 'CNK', nome: 'Canapi' },
	    { sigla: 'DGA', nome: 'Delmiro Gouveia' },
	    { sigla: 'IHP', nome: 'Inhapi' },
	    { sigla: 'MGR', nome: 'Mata Grande' },
	    { sigla: 'OHD', nome: 'Olho D\'Água do Casado' },
	    { sigla: 'PRCH', nome: 'Pariconha' },
	    { sigla: 'PYH', nome: 'Piranhas' }
	],

    'PE': [
        { sigla: 'SGI', nome: 'Salgueiro' },
        { sigla: 'VER', nome: 'Veredinha' }
    ],
    'PI': [
        { sigla: 'AOX', nome: 'Alto Longa' },
        { sigla: 'ZRA', nome: 'Zé Doca' }
    ],
    'BA': [
	    { sigla: 'CAR', nome: 'Camaçari' },
	    { sigla: 'CIS', nome: 'Candeias' },
	    { sigla: 'CAU', nome: 'Catu' },
	    { sigla: 'DSA', nome: 'Dias D\'Ávila' },
	    { sigla: 'IAP', nome: 'Itaparica' },
	    { sigla: 'LFS', nome: 'Lauro de Freitas' },
	    { sigla: 'MDY', nome: 'Madre de Deus' },
	    { sigla: 'MJO', nome: 'Mata de São João' },
	    { sigla: 'PJC', nome: 'Pojuca' },
	    { sigla: 'SDR', nome: 'Salvador' },
	    { sigla: 'SFN', nome: 'São Francisco do Conde' },
	    { sigla: 'SSE', nome: 'São Sebastião do Passe' },
	    { sigla: 'SMF', nome: 'Simões Filho' },
	    { sigla: 'VCZ', nome: 'Vera Cruz' },
	    { sigla: 'ALM', nome: 'Almadina' },
	    { sigla: 'ATW', nome: 'Arataca' },
	    { sigla: 'BPO', nome: 'Barro Preto' },
	    { sigla: 'BUE', nome: 'Buerarema' },
	    { sigla: 'COC', nome: 'Coaraci' },
	    { sigla: 'FMV', nome: 'Firmino Alves' },
	    { sigla: 'FAL', nome: 'Floresta Azul' },
	    { sigla: 'ICR', nome: 'Ibiracará' },
	    { sigla: 'IBC', nome: 'Ibicuí' },
	    { sigla: 'IUI', nome: 'Iguaí' },
	    { sigla: 'ILH', nome: 'Ilhéus' },
	    { sigla: 'ITB', nome: 'Itabuna' },
	    { sigla: 'IJL', nome: 'Itaju do Colônia' },
	    { sigla: 'IJP', nome: 'Itajuípe' },
	    { sigla: 'YPE', nome: 'Itapé' },
	    { sigla: 'ITT', nome: 'Itapitanga' },
	    { sigla: 'IRR', nome: 'Itororó' },
	    { sigla: 'JSI', nome: 'Jussari' },
	    { sigla: 'NCO', nome: 'Nova Canaã' },
	    { sigla: 'SVT', nome: 'Santa Cruz da Vitória' },
	    { sigla: 'SVQ', nome: 'São José da Vitória' },
	    { sigla: 'WNA', nome: 'Una' },
	    { sigla: 'UUU', nome: 'Uruçuca' },
	    { sigla: 'EUS', nome: 'Eunápolis' },
	    { sigla: 'GNG', nome: 'Guaratinga' },
	    { sigla: 'IBH', nome: 'Itabela' },
	    { sigla: 'IMM', nome: 'Itagimirim' },
	    { sigla: 'IEY', nome: 'Itapebi' },
	    { sigla: 'PGU', nome: 'Porto Seguro' },
	    { sigla: 'SZB', nome: 'Santa Cruz Cabrália' },
	    { sigla: 'ALC', nome: 'Alcobaça' },
	    { sigla: 'CRV', nome: 'Caravelas' },
	    { sigla: 'IBP', nome: 'Ibirapuã' },
	    { sigla: 'IMJ', nome: 'Itamaraju' },
	    { sigla: 'IHM', nome: 'Itanhém' },
	    { sigla: 'JUC', nome: 'Jucuruçu' },
	    { sigla: 'LED', nome: 'Lajedão' },
	    { sigla: 'MSN', nome: 'Medeiros Neto' },
	    { sigla: 'MUI', nome: 'Mucuri' },
	    { sigla: 'NVV', nome: 'Nova Viçosa' },
	    { sigla: 'PRD', nome: 'Prado' },
	    { sigla: 'TAF', nome: 'Teixeira de Freitas' },
	    { sigla: 'VEE', nome: 'Vereda' },
	    { sigla: 'BLE', nome: 'Belmonte' },
	    { sigla: 'CCN', nome: 'Camacan' },
	    { sigla: 'CVS', nome: 'Canavieiras' },
	    { sigla: 'IRM', nome: 'Itarantim' },
	    { sigla: 'MAE', nome: 'Mascote' },
	    { sigla: 'PSL', nome: 'Pau Brasil' },
	    { sigla: 'POG', nome: 'Potiraguá' },
	    { sigla: 'SUY', nome: 'Santa Luzia' },
	    { sigla: 'AEL', nome: 'Aurelino Leal' },
	    { sigla: 'BCH', nome: 'Barra do Rocha' },
	    { sigla: 'CMM', nome: 'Camamu' },
	    { sigla: 'GDU', nome: 'Gandu' },
	    { sigla: 'GGG', nome: 'Gongogi' },
	    { sigla: 'IIP', nome: 'Ibirapitanga' },
	    { sigla: 'IRT', nome: 'Ibirataia' },
	    { sigla: 'IGH', nome: 'Igrapiúna' },
	    { sigla: 'IRE', nome: 'Itacaré' },
	    { sigla: 'IMY', nome: 'Itamari' },
	    { sigla: 'IUR', nome: 'Itubera' },
	    { sigla: 'MRU', nome: 'Marau' },
	    { sigla: 'NIA', nome: 'Nilo Peçanha' },
	    { sigla: 'NIB', nome: 'Nova Ibia' },
	    { sigla: 'PDQ', nome: 'Piraí do Norte' },
	    { sigla: 'PTQ', nome: 'Presidente Tancredo Neves' },
	    { sigla: 'TEN', nome: 'Teolândia' },
	    { sigla: 'UIA', nome: 'Ubaitaba' },
	    { sigla: 'UAT', nome: 'Ubata' },
	    { sigla: 'WGS', nome: 'Wenceslau Guimarães' },
	    { sigla: 'AIQ', nome: 'Aiquara' },
	    { sigla: 'APE', nome: 'Apuarema' },
	    { sigla: 'CVO', nome: 'Cravolândia' },
	    { sigla: 'DMA', nome: 'Dário Meira' },
	    { sigla: 'IPW', nome: 'Ipiaú' },
	    { sigla: 'IRJ', nome: 'Irajuba' },
	    { sigla: 'YGI', nome: 'Itagi' },
	    { sigla: 'IGB', nome: 'Itagiba' },
	    { sigla: 'IQA', nome: 'Itaquara' },
	    { sigla: 'IIC', nome: 'Itiruçu' },
	    { sigla: 'JGQ', nome: 'Jaguaquara' },
	    { sigla: 'JEE', nome: 'Jequié' },
	    { sigla: 'JTN', nome: 'Jitaúna' },
	    { sigla: 'LFE', nome: 'Lafaete Coutinho' },
	    { sigla: 'LTL', nome: 'Lajedo do Tabocal' },
	    { sigla: 'MVO', nome: 'Manoel Vitorino' },
	    { sigla: 'MAS', nome: 'Maracás' },
	    { sigla: 'NOI', nome: 'Nova Itarana' },
	    { sigla: 'PLY', nome: 'Planaltino' },
	    { sigla: 'SAT', nome: 'Santa Inês' },
	    { sigla: 'BXD', nome: 'Baixa Grande' },
	    { sigla: 'CKX', nome: 'Caém' },
	    { sigla: 'CDG', nome: 'Caldeirão Grande' },
	    { sigla: 'CCG', nome: 'Capim Grosso' },
	    { sigla: 'JBN', nome: 'Jacobina' },
	    { sigla: 'MJU', nome: 'Macajuba' },
	    { sigla: 'MRY', nome: 'Mairi' },
	    { sigla: 'MGN', nome: 'Miguel Calmon' },
	    { sigla: 'MIN', nome: 'Mirangaba' },
	    { sigla: 'MHU', nome: 'Morro do Chapéu' },
	    { sigla: 'MNO', nome: 'Mundo Novo' },
	    { sigla: 'OUL', nome: 'Ourolândia' },
	    { sigla: 'PRI', nome: 'Piritiba' },
	    { sigla: 'PNF', nome: 'Ponto Novo' },
	    { sigla: 'QXR', nome: 'Quixabeira' },
	    { sigla: 'SUJ', nome: 'São José do Jacuípe' },
	    { sigla: 'SUX', nome: 'Saúde' },
	    { sigla: 'SEL', nome: 'Serrolândia' },
	    { sigla: 'TAP', nome: 'Tapiramutá' },
	    { sigla: 'VDA', nome: 'Várzea da Roça' },
	    { sigla: 'VZC', nome: 'Várzea do Poço' },
	    { sigla: 'VOA', nome: 'Várzea Nova' },
	    { sigla: 'AED', nome: 'América Dourada' },
	    { sigla: 'BDS', nome: 'Barra do Mendes' },
	    { sigla: 'BLT', nome: 'Barro Alto' },
	    { sigla: 'CFM', nome: 'Cafarnaum' },
	    { sigla: 'CNR', nome: 'Canarana' },
	    { sigla: 'CAL', nome: 'Central' },
	    { sigla: 'IBB', nome: 'Ibipetá' },
	    { sigla: 'IIY', nome: 'Ibititá' },
	    { sigla: 'IEE', nome: 'Irecê' },
	    { sigla: 'JDY', nome: 'João Dourado' },
	    { sigla: 'JSS', nome: 'Jussara' },
	    { sigla: 'LPO', nome: 'Lapão' },
	    { sigla: 'MUD', nome: 'Mulungu do Morro' },
	    { sigla: 'PDN', nome: 'Presidente Dutra' },
	    { sigla: 'SYK', nome: 'São Gabriel' },
	    { sigla: 'UII', nome: 'Uibaí' },
	    { sigla: 'BAA', nome: 'Barra' },
	    { sigla: 'GOU', nome: 'Gentio do Ouro' },
	    { sigla: 'IGD', nome: 'Itaguçu da Bahia' },
	    { sigla: 'XXQ', nome: 'Xique-Xique' },
	    { sigla: 'CSV', nome: 'Casa Nova' },
	    { sigla: 'CRX', nome: 'Curacá' },
	    { sigla: 'JUO', nome: 'Juazeiro' },
	    { sigla: 'SHB', nome: 'Sobradinho' },
	    { sigla: 'UAU', nome: 'Uauá' },
	    { sigla: 'ADK', nome: 'Andorinha' },
	    { sigla: 'AV S', nome: 'Antônio Gonçalves' },
	    { sigla: 'CFS', nome: 'Campo Formoso' },
	    { sigla: 'FDA', nome: 'Filadélfia' },
	    { sigla: 'IIB', nome: 'Itiúba' },
	    { sigla: 'JGA', nome: 'Jaguarari' },
	    { sigla: 'PDC', nome: 'Pindobaçu' },
	    { sigla: 'SBM', nome: 'Senhor do Bonfim' },
	    { sigla: 'UMS', nome: 'Umburanas' },
	    { sigla: 'CGR', nome: 'Campo Alegre de Lourdes' },
	    { sigla: 'PID', nome: 'Pilão Arcado' },
	    { sigla: 'REM', nome: 'Remanso' },
	    { sigla: 'SES', nome: 'Sento Sé' },
	    { sigla: 'AFA', nome: 'Água Fria' },
	    { sigla: 'ARG', nome: 'Amélia Rodrigues' },
	    { sigla: 'AEX', nome: 'Anguera' },
	    { sigla: 'ATC', nome: 'Antônio Cardoso' },
	    { sigla: 'CFA', nome: 'Conceição da Feira' },
	    { sigla: 'CJP', nome: 'Conceição do Jacuípe' },
	    { sigla: 'CEI', nome: 'Coração de Maria' },
	    { sigla: 'FSA', nome: 'Feira de Santana' },
	    { sigla: 'IEC', nome: 'Ipecaetá' },
    ],
    'SE': [
        { sigla: 'AJU', nome: 'Aracaju' },
        { sigla: 'SDS', nome: 'Simão Dias' }
    ],
    'MA': [
        { sigla: 'ALN', nome: 'Alcântara' },
        { sigla: 'VGE', nome: 'Vitória do Mearim' }
    ]
};

// Função para filtrar cidades com base no estado selecionado
function filtrarCidades() {
    const estadoSelecionado = document.getElementById('estado').value;
    const cidadeSelect = document.getElementById('cidade');

    // Limpa as opções de cidade
    cidadeSelect.innerHTML = '<option value="">Selecione uma cidade</option>';

    // Popula as cidades relacionadas ao estado selecionado
    if (estadoSelecionado && cidadesPorEstado[estadoSelecionado]) {
        cidadesPorEstado[estadoSelecionado].forEach(cidade => {
            const option = document.createElement('option');
            option.value = cidade.sigla;
            option.textContent = cidade.nome;
            cidadeSelect.appendChild(option);
        });
    }
}

// Função para gerar os títulos
function gerarTitulos() {
    const categoria = document.getElementById("categoria").value;
    const servico = document.getElementById("servico").value;
    const cnpj = document.getElementById("cnpj").value;
    const contrato = document.getElementById("contrato").value;
    const ponto = document.getElementById("ponto").value;
    const estado = document.getElementById("estado").value;
    const cidade = document.getElementById("cidade").value;
    const empresa = document.getElementById("empresa").value;

    const projetoPai = `${categoria}-${servico}-${cnpj}-${estado}-${empresa}`;
    const projetoFilho = `${categoria}-${servico}-${contrato}-${ponto}-${cidade}-${empresa}`;
    document.getElementById("projetoPai").innerText = projetoPai;
    document.getElementById("projetoFilho").innerText = projetoFilho;

    document.getElementById("resultModal").style.display = "flex"; // Exibe o modal
}

// Função para copiar textos
function copiarTexto(id) {
    const texto = document.getElementById(id).innerText;
    navigator.clipboard.writeText(texto).then(() => {
        alert("Texto copiado com sucesso!");
    });
}

// Função para fechar o modal
function fecharModal() {
    document.getElementById("resultModal").style.display = "none"; // Oculta o modal
}

